import { test, expect } from '@playwright/test';

test('durable Agent detail remains selected through interruption and resume; Job reaches final settlement', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' || message.type() === 'warning') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:5174/test/fixtures/activity.html');
  await expect(page).toHaveTitle('rustX Jobs and Agents');
  const agent = page.locator('[data-agent-id="agent-worker"]');
  await expect(agent).toHaveAttribute('data-activation-id', 'activation-a');
  await agent.getByRole('button', { name: 'Transcript', exact: true }).click();
  await expect(agent.getByRole('heading', { name: 'Final report' })).toBeVisible();
  await agent.getByRole('button', { name: 'Interrupt', exact: true }).click();
  await expect(agent.getByText('Inactive', { exact: true })).toBeVisible();
  await agent.getByRole('textbox', { name: 'Message Agent Worker' }).fill('Continue reviewing');
  await agent.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(agent).toHaveAttribute('data-activation-id', 'activation-b');
  await expect(agent.getByRole('heading', { name: 'Final report' })).toBeVisible();
  await expect(agent).toHaveCount(1);
  const job = page.getByRole('region', { name: 'Job Build' });
  await job.getByRole('button', { name: 'Cancel Job', exact: true }).click();
  await expect(job.getByRole('button', { name: 'Cancel Job', exact: true })).toBeDisabled();
  await job.getByRole('button', { name: /Build/ }).click();
  await expect(job.getByText(/Process settled/)).toBeVisible();
  await expect(page.locator('vite-error-overlay')).toHaveCount(0);
  expect(errors).toEqual([]);
  await page.screenshot({ path: '/tmp/rustx-411-web-activity-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/rustx-411-web-activity-mobile.png', fullPage: true });
});
