import { connectionAction, closeSettings } from './shell-actions';
import { routeWorkspaceHost } from './workspace-host';
import { test, expect } from '@playwright/test';
import { startDogfood } from './dogfood-server';
import { AppServerHost } from '../../../tui/src/app-server/host';

test('native history, rich settlement, real image decode/lightbox, reconnect and native upload receipts', async ({ page }) => {
  const fixture = await startDogfood('web_chat_history');
  await page.addInitScript(() => {
    const urls = new Set<string>();
    const create = URL.createObjectURL.bind(URL), revoke = URL.revokeObjectURL.bind(URL);
    URL.createObjectURL = value => { const url = create(value); urls.add(url); return url; };
    URL.revokeObjectURL = url => { urls.delete(url); revoke(url); };
    Object.defineProperty(window, 'acceptanceObjectUrls', { get: () => urls.size });
  });
  const urlCount = () => page.evaluate(() => (window as unknown as { acceptanceObjectUrls: number }).acceptanceObjectUrls);
  let passed = false;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    // Build durable history via typed native admission before the browser attaches.
    const remote = await AppServerHost.connectRemote({ endpoint: fixture.endpoint, token: fixture.token });
    const created = await remote.client.call('session/create', { settings: { cwd: fixture.workspaceA } }, 'session_transition');
    const id = created.session.id;
    const attached = await remote.client.call('session/attach', { session_id: id }, 'attached');
    await expect(remote.client.call('artifact/read', { target: attached.target, artifact_id: 'artifact_999' }, 'artifact_bytes')).rejects.toThrow();
    for (let i = 0; i < 34; i++) {
      await remote.client.call('turn/start', { target: attached.target, content: [{ type: 'text', text: `History ${i}` }] }, 'inbound_accepted');
      await expect.poll(async () => {
        const current = await remote.client.call('session/snapshot', { target: attached.target }, 'snapshot');
        return current.snapshot.attempt?.phase.type === 'settled' && current.snapshot.messages.some(message => message.role === 'assistant' && message.content.some(block => block.type === 'text' && block.text === `Answer ${i}`));
      }).toBe(true);
    }
    const traceBeforeBrowser = (await remote.client.call('session/trace', { target: attached.target, limit: 32 }, 'trace')).page;
    expect(traceBeforeBrowser.entries).toHaveLength(32);
    await remote.client.call('session/detach', { target: attached.target }, 'detached');
    await remote.shutdown();
    await routeWorkspaceHost(page, fixture);
    await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(fixture.endpoint);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.locator(`button[data-session-id="${id}"]`).click();
    await expect(page.getByRole('button', { name: 'Load earlier', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Load earlier', exact: true }).scrollIntoViewIfNeeded();
    const firstKey = await page.locator('[data-chat-anchor-key]').first().getAttribute('data-chat-anchor-key');
    const anchor = page.locator(`[data-chat-anchor-key=${JSON.stringify(firstKey)}]`);
    const anchorTop = await anchor.evaluate(el => el.getBoundingClientRect().top);
    await expect(page.getByText('Answer 0', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Load earlier', exact: true }).click();
    await expect(page.getByText('Answer 0', { exact: true })).toHaveCount(1);
    await expect(page.getByRole('button', { name: 'Load earlier', exact: true })).toHaveCount(0);
    expect(Math.abs(await anchor.evaluate(el => el.getBoundingClientRect().top) - anchorTop)).toBeLessThan(2);
    // WEB-03 uses this same native Session, transcript and provider scenario.
    await page.getByRole('tab', { name: 'Trajectory', exact: true }).click();
    const trajectory = page.getByRole('region', { name: 'Trajectory', exact: true });
    const ledger = trajectory.getByRole('table', { name: 'Trace ledger' });
    await expect(ledger).toHaveAttribute('aria-rowcount', '32');
    await expect.poll(() => ledger.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2);
    await ledger.evaluate(el => { el.scrollTop = 200; el.dispatchEvent(new Event('scroll')); });
    const traceAnchor = trajectory.locator('[data-trace-id]').filter({ has: page.locator('button') }).nth(8);
    const traceAnchorId = await traceAnchor.getAttribute('data-trace-id');
    const traceAnchorTop = await traceAnchor.evaluate(el => el.getBoundingClientRect().top);
    await trajectory.getByRole('button', { name: 'Load older Trace', exact: true }).click();
    await expect(ledger).toHaveAttribute('aria-rowcount', '64');
    expect(await trajectory.locator('[data-trace-id]').count()).toBeLessThan(64);
    await expect.poll(async () => Math.abs(await trajectory.locator(`[data-trace-id="${traceAnchorId}"]`).evaluate(el => el.getBoundingClientRect().top) - traceAnchorTop)).toBeLessThan(2);
    const requestRecord = traceBeforeBrowser.entries.find(entry => entry.request)!;
    await trajectory.getByLabel('Search loaded Trace').fill(requestRecord.request!.request_id);
    await trajectory.locator(`[data-trace-id="${requestRecord.id}"] button`).click();
    const inspector = trajectory.getByLabel('Trace record inspector');
    await expect(inspector).toContainText(requestRecord.request!.request_id);
    await expect(inspector).toContainText('Logical Step');
    await inspector.getByRole('tab', { name: 'Input', exact: true }).click();
    await expect(inspector).toContainText('Redacted');
    expect(await inspector.innerText()).not.toContain(fixture.workspaceA);
    await trajectory.getByLabel('Search loaded Trace').fill('');
    await inspector.getByRole('button', { name: 'Close record' }).click();
    await closeSettings(page); await page.getByRole('tab', { name: 'Chat', exact: true }).click();
    await page.getByLabel('Message', { exact: true }).fill('Rich reply');
    await page.getByRole('button', { name: 'Send', exact: true }).click();
    await fixture.gate('settle-chat');
    await expect(page.getByRole('heading', { name: 'Rich reply' })).toHaveCount(1);
    // Reconstruct a bounded latest window while the same native attempt is
    // held mid-stream, then page its history without changing live ownership.
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await page.getByRole('button', { name: 'Load earlier', exact: true }).click();
    await expect(page.getByText('Answer 0', { exact: true })).toHaveCount(1);
    await expect(page.locator('.attempt-status')).toContainText('running');

    await page.getByRole('tab', { name: 'Trajectory', exact: true }).click();
    await expect.poll(() => ledger.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2);
    await expect(trajectory.getByRole('table')).toContainText('running');
    // A reader away from the tail owns their position while live repair runs.
    await ledger.evaluate(el => { el.scrollTop = 0; el.dispatchEvent(new Event('scroll')); });
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await ledger.evaluate(el => { el.scrollTop = el.scrollHeight; el.dispatchEvent(new Event('scroll')); });
    await expect(trajectory.getByRole('table')).toContainText('running');
    await ledger.evaluate(el => { el.scrollTop = 0; el.dispatchEvent(new Event('scroll')); });
    const beforeSettlement = Number(await ledger.getAttribute('aria-rowcount'));
    await fixture.release('settle-chat');
    await expect.poll(async () => Number(await ledger.getAttribute('aria-rowcount'))).toBeGreaterThan(beforeSettlement);
    expect(await ledger.evaluate(el => el.scrollTop)).toBe(0);
    await closeSettings(page); await page.getByRole('tab', { name: 'Chat', exact: true }).click();
    await expect(page.getByText('Settled', { exact: true })).toHaveCount(1);
    await expect(page.locator('[aria-label^="Streaming ·"]')).toHaveCount(0);
    await expect(page.getByRole('table')).toHaveCount(1);
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(page.getByRole('heading', { name: 'Rich reply' })).toHaveCount(1);
    await page.getByRole('button', { name: 'Load earlier', exact: true }).click();
    await expect(page.getByText('Answer 0', { exact: true })).toHaveCount(1);
    await page.getByLabel('Message', { exact: true }).fill('Keep this draft');
    await page.getByLabel('Attach files').setInputFiles({ name: 'note.txt', mimeType: 'text/plain', buffer: Buffer.from('file content') });
    await page.getByRole('button', { name: 'Send', exact: true }).click();
    await expect(page.getByText('Uploaded workspace file received.', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Message', { exact: true })).toHaveValue('');
    await expect(page.getByLabel('Canonical conversation').getByText('note.txt', { exact: true })).toBeVisible();
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(page.getByLabel('Canonical conversation').getByText('note.txt', { exact: true })).toBeVisible();
    await page.getByLabel('Message', { exact: true }).fill('Image please');
    await page.getByRole('button', { name: 'Send', exact: true }).click();
    const canonical = page.getByLabel('Canonical conversation');
    const load = canonical.getByRole('button', { name: 'Load attachment' });
    await expect(canonical.locator('[data-tool-call-id="chat-image"]')).toHaveCount(1);
    await expect(load).toHaveCount(1);
    const decode = async () => {
      await load.click();
      const image = canonical.locator('img');
      await expect(image).toBeVisible();
      await expect.poll(() => image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0 && node.naturalHeight > 0)).toBe(true);
      await image.click();
      const original = page.getByRole('dialog').locator('img');
      await expect(original).toBeVisible();
      await expect.poll(() => original.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true);
      await page.keyboard.press('Escape');
    };
    await decode();
    expect(await urlCount()).toBe(1);
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(load).toHaveCount(1);
    expect(await urlCount()).toBe(0);
    await decode();
    expect(await urlCount()).toBe(1);
    await page.getByRole('tab', { name: 'Trajectory', exact: true }).click();
    await expect.poll(urlCount).toBe(0);
    await trajectory.getByLabel('Search loaded Trace').fill('chat-image');
    await trajectory.getByLabel('Trace category').selectOption('tool');
    const tool = trajectory.locator('[data-trace-id]');
    await expect(tool).toHaveCount(1);
    const stableToolId = await tool.getAttribute('data-trace-id');
    await tool.locator('button').click();
    await expect(trajectory.getByLabel('Trace record inspector')).toContainText('chat-image');
    await page.screenshot({ path: 'test-results/trajectory-inspector.png', fullPage: true });
    await connectionAction(page, 'Reconnect');
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(trajectory.locator(`[data-trace-id="${stableToolId}"]`)).toHaveCount(1);
    expect(await trajectory.innerText()).not.toContain(fixture.workspaceA);
    await closeSettings(page); await page.getByRole('tab', { name: 'Chat', exact: true }).click();
    expect((await fixture.control('requests')).requests).toHaveLength(37);
    await page.screenshot({ path: 'test-results/chat-history.png', fullPage: true });
    expect(errors).toEqual([]); passed = true;
  } catch (error) {
    await test.info().attach('native-image-diagnostics', { body: JSON.stringify({ text: await page.locator('body').innerText(), diagnostics: fixture.diagnostics(), requests: await fixture.control('requests') }), contentType: 'application/json' });
    throw error;
  } finally { await page.close(); await fixture.stop(passed); }
});
