import { test, expect } from '@playwright/test';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { startDogfood } from './dogfood-server';

test('typed selectors, native upload-bearing retry branch, original lineage and independent Fork', async ({ page }) => {
  const fixture = await startDogfood('web_commands');
  let passed = false;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const message = page.getByRole('textbox', { name: 'Message', exact: true });
  const facts = page.getByLabel('Runtime facts', { exact: true });
  const command = async (name: string) => { await message.fill(`/${name}`); await message.press('Enter'); return page.getByRole('dialog', { name: `/${name}`, exact: true }); };
  const settled = () => expect(page.locator('.attempt-status')).toContainText('settled');
  try {
    await page.goto('/'); await expect(page).toHaveTitle(/rustX/);
    await page.getByLabel('WebSocket endpoint').fill(fixture.endpoint);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await page.getByLabel('Session cwd').fill(fixture.workspaceA);
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(message).toBeEnabled();
    const originalId = JSON.parse(await facts.innerText()).SessionId as string;
    const originalConversation = JSON.parse(await facts.innerText()).ConversationId as string;
    let popup = await command('model');
    await popup.getByLabel('Filter options').fill('second');
    await popup.getByRole('option', { name: /fixture\/second-model/ }).click();
    await expect(popup).toHaveCount(0); await expect(message).toHaveValue('');
    await expect(facts).toContainText('fixture/second-model');
    popup = await command('permission');
    await popup.getByRole('option', { name: 'Full access', exact: true }).click();
    await expect(popup).toHaveCount(0); await expect(facts).toContainText('full_access');
    popup = await command('model'); await popup.getByLabel('Filter options').press('Escape');
    await expect(popup).toHaveCount(0); await expect(message).toBeFocused();
    await expect(message).toHaveValue('/model');
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(facts).toContainText('fixture/second-model');
    await expect(facts).toContainText('full_access');
    await message.fill('/not-a-command'); await message.press('Enter');
    await expect(page.getByRole('alert')).toContainText('Unsupported command');
    await expect(message).toHaveValue('/not-a-command');
    await message.fill('Regenerate my uploaded note');
    await page.getByLabel('Attach files').setInputFiles({ name: 'note.txt', mimeType: 'text/plain', buffer: Buffer.from('Owned by native Session') });
    await expect(page.getByText('Uploaded', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Send', exact: true }).click();
    await expect(page.getByText('Original native answer', { exact: true })).toBeVisible(); await settled();
    await page.getByRole('button', { name: 'Retry / Regenerate', exact: true }).click();
    await page.getByRole('dialog', { name: 'Retry / Regenerate', exact: true }).getByRole('option', { name: /Regenerate my uploaded note/ }).click();
    await expect(page.getByText('Regenerated native answer', { exact: true })).toBeVisible(); await settled();
    expect(JSON.parse(await facts.innerText()).SessionId).toBe(originalId);
    expect(JSON.parse(await facts.innerText()).ConversationId).not.toBe(originalConversation);
    const transcript = page.getByLabel('Canonical conversation');
    await expect(transcript.getByText('Original native answer', { exact: true })).toHaveCount(0);
    await expect(transcript.getByText('Regenerate my uploaded note', { exact: true })).toHaveCount(1);
    await page.screenshot({ path: 'test-results/commands-retry-desktop.png' });
    await page.getByRole('button', { name: 'Session tree', exact: true }).click();
    await page.getByRole('dialog', { name: 'Session tree', exact: true }).getByRole('option').filter({ hasText: originalConversation }).click();
    await expect(transcript.getByText('Original native answer', { exact: true })).toBeVisible();
    await expect(transcript.getByText('Regenerated native answer', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Fork', exact: true }).click();
    await page.getByRole('dialog', { name: '/fork', exact: true }).getByRole('option', { name: /Regenerate my uploaded note/ }).click();
    await expect(message).toHaveValue('Regenerate my uploaded note');
    const forkId = JSON.parse(await facts.innerText()).SessionId as string;
    expect(forkId).not.toBe(originalId);
    await expect(transcript.getByText('Original native answer', { exact: true })).toHaveCount(0);
    await expect(page.getByText(/Native restored upload batch/)).toBeVisible();
    // Native #319 copies the editor-boundary upload before publishing the child.
    const root = join(fixture.workspaceA, '.agents/uploads', forkId);
    const batches = readdirSync(root);
    expect(batches).toHaveLength(1);
    expect(readFileSync(join(root, batches[0], 'note.txt'), 'utf8')).toBe('Owned by native Session');
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(message).toBeEnabled();
    // Live settings are Conversation-owned. A new cold lineage uses the native
    // Session/launch configuration, never a browser copy of the old live values.
    await expect(facts).toContainText('fixture/console-model');
    await expect(facts).toContainText('policy');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Remove draft upload' }).click();
    popup = await command('model'); await expect(popup.getByRole('option', { name: /fixture\/second-model/ })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/commands-selector-mobile.png' });
    expect(errors).toEqual([]); passed = true;
  } finally { await fixture.stop(passed); }
});
