import { test, expect } from '@playwright/test';
const origin = `http://127.0.0.1:${process.env.RUSTX_E2E_FIXTURE_PORT ?? 5174}`;
for (const width of [390, 1440]) for (const theme of ['light', 'dark']) test(`grouped composer add menu ${width} ${theme}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.addInitScript(theme => { localStorage.setItem('rustx-locale-v1', 'zh'); localStorage.setItem('rustx-appearance-v1', theme); }, theme);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${origin}/test/fixtures/agent.html?mode=composer`);
  const input = page.getByRole('textbox', { name: '消息', exact: true });
  await input.fill('保留这段草稿');
  await page.getByRole('button', { name: '添加', exact: true }).click();
  const menu = page.getByRole('listbox'); await expect(menu).toBeVisible();
  await expect(page.getByRole('button', { name: '添加附件', exact: true })).toHaveCount(0);
  await expect(menu.locator('svg')).toHaveCount(await menu.getByRole('option').count());
  await expect(page.locator('#command-file')).toHaveAttribute('aria-selected', 'true');
  const bounds = (await menu.boundingBox())!, card = (await page.locator('[data-composer-card]').boundingBox())!;
  expect(bounds.y).toBeGreaterThanOrEqual(0); expect(Math.abs(bounds.width - card.width)).toBeLessThan(2);
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(card.y);
  await page.screenshot({ path: `/tmp/rustx-add-${theme}-${width}.png` });
  const picker = page.waitForEvent('filechooser');
  if (width === 390) await input.press('Enter'); else await page.locator('#command-file').click();
  await (await picker).setFiles({ name: 'menu.txt', mimeType: 'text/plain', buffer: Buffer.from('attachment from add menu') });
  await expect(menu).toHaveCount(0); await expect(input).toHaveValue('保留这段草稿');
  await expect(page.getByText('menu.txt', { exact: true })).toBeVisible();
  await input.fill('/mdl'); await expect(page.locator('#command-model')).toBeVisible();
  await expect(page.locator('#command-file')).toHaveCount(0);
  await input.press('Escape'); await expect(input).toHaveValue('/mdl');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await input.fill('保留草稿');
  await page.setViewportSize({ width, height: 480 });
  await page.getByRole('button', { name: '添加', exact: true }).click();
  await input.press('ArrowUp');
  await expect(page.locator('#command-tools')).toHaveAttribute('aria-selected', 'true');
  await expect.poll(() => menu.evaluate(node => node.scrollTop)).toBeGreaterThan(0);
  expect((await menu.boundingBox())!.y).toBeGreaterThanOrEqual(0);
  await input.press('ArrowDown');
  await expect(page.locator('#command-file')).toHaveAttribute('aria-selected', 'true');
  await input.press('Escape');
  expect(errors).toEqual([]);
});
