import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { startDogfood } from './dogfood-server';

test('two real rustX Sessions, browser loss, native interactions, raw wire, and cold configuration resolution', async ({ page }) => {
  const fixture = await startDogfood();
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const connect = async () => {
    await page.getByLabel('WebSocket endpoint').fill(`${fixture.endpoint}/`);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
  };
  const send = async (text: string) => { await page.getByRole('textbox', { name: 'Message', exact: true }).fill(text); await page.getByRole('button', { name: 'Send', exact: true }).click(); };
  const reload = async () => { await page.reload(); await connect(); };
  let passed = false;
  try {
    await page.goto('/'); await expect(page).toHaveTitle('rustX Developer Console');
    await expect(page.getByRole('heading', { name: 'Sessions, in motion.' })).toBeVisible();
    await connect();
    await page.getByLabel('Session cwd').fill(fixture.workspaceA);
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toHaveText(`${fixture.workspaceA} · attached`);
    const idA = await page.locator('.session-toolbar strong').innerText();
    await page.getByLabel('Session cwd').fill(fixture.workspaceB); await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toHaveText(`${fixture.workspaceB} · attached`);
    const idB = await page.locator('.session-toolbar strong').innerText();
    await expect(page.getByRole('tab')).toHaveCount(2);
    await page.getByRole('tab', { name: idA.slice(0, 16), exact: true }).click();
    await send('Long action in A'); await fixture.gate('finish-a');
    await expect(page.getByText('A is running.', { exact: true })).toBeVisible();
    await page.getByRole('tab', { name: idB.slice(0, 16), exact: true }).click(); await send('Use B while A runs');
    await expect(page.getByText('B stayed responsive.', { exact: true })).toBeVisible();
    await page.getByRole('tab', { name: idA.slice(0, 16), exact: true }).click();
    await page.getByRole('button', { name: 'Disconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('disconnected');
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await expect(page.getByText('A is running.', { exact: true })).toBeVisible();
    await reload(); await expect(page.getByText('A is running.', { exact: true })).toBeVisible();
    await fixture.release('finish-a'); await expect(page.getByText('A is running. A finished.', { exact: true })).toBeVisible();
    await send('Approval please'); await expect(page.getByRole('button', { name: 'Allow once' })).toBeEnabled();
    await page.getByRole('button', { name: 'Disconnect', exact: true }).click(); await reload();
    await expect(page.getByRole('button', { name: 'Allow once' })).toBeEnabled(); await page.getByRole('button', { name: 'Allow once' }).click();
    await expect(page.getByText('Approval completed.', { exact: true })).toBeVisible();
    await send('Questionnaire please'); await expect(page.getByRole('region', { name: 'Questionnaire' })).toBeVisible();
    await reload(); await page.getByRole('radio', { name: 'Keep native', exact: true }).click(); await page.getByRole('button', { name: 'Submit answers' }).click();
    await expect(page.getByText('Questionnaire completed.', { exact: true })).toBeVisible();
    await send('Publish while detached'); await fixture.gate('publish-question');
    await page.getByRole('button', { name: 'Detach', exact: true }).click(); await expect(page.locator('.session-toolbar small')).toContainText('detached');
    await fixture.release('publish-question');
    await fixture.control('observations/await?kind=response_completed&count=7&timeoutMs=30000');
    await page.getByRole('button', { name: 'Attach / cold resume' }).click();
    await expect(page.getByRole('region', { name: 'Questionnaire' })).toBeVisible();
    await page.getByRole('radio', { name: 'Keep native', exact: true }).click(); await page.getByRole('button', { name: 'Submit answers' }).click();
    await expect(page.getByText('Detached question completed.', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Runtime facts')).toContainText('console-model');
    fixture.writeSettings('second-model');
    await page.getByRole('button', { name: 'Resync', exact: true }).click();
    await expect(page.getByLabel('Runtime facts')).toContainText('console-model');
    await page.getByRole('button', { name: 'Unload runtime', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText('unloaded');
    await page.getByRole('button', { name: 'Attach / cold resume' }).click();
    await expect(page.getByLabel('Runtime facts')).toContainText('second-model');
    await expect(page.getByText('A is running. A finished.', { exact: true })).toBeVisible();
    await expect(page.locator('.session-toolbar small')).toContainText(fixture.workspaceA);
    expect(readFileSync(fixture.settings, 'utf8')).toContain('second-model');
    await page.getByLabel('Method filter').fill('session/attach');
    await expect(page.locator('.protocol-log')).toContainText('session/attach');
    await page.getByRole('button', { name: 'Pause log' }).click(); await expect(page.getByRole('button', { name: 'Resume log' })).toBeVisible();
    await page.getByRole('button', { name: 'Resume log' }).click();
    await page.screenshot({ path: 'test-results/console-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: 'test-results/console-mobile.png', fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain(fixture.token);
    expect(await page.locator('body').innerText()).not.toContain('fake-provider-only');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('tab', { name: idB.slice(0, 16), exact: true }).click();
    await page.getByRole('button', { name: 'Unload runtime', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText('unloaded');
    await page.getByRole('button', { name: 'Delete session-2', exact: true }).click();
    await expect(page.getByRole('region', { name: 'Confirm Session deletion' })).toBeVisible();
    await page.getByRole('button', { name: 'Confirm delete', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('"status": "deleted"');
    await expect(page.getByRole('button', { name: 'Open session-2', exact: true })).toHaveCount(0);
    await expect(page.getByRole('tab')).toHaveCount(1);
    await expect(page.locator('.session-toolbar strong')).toHaveText(idA);
    expect(errors).toEqual([]); passed = true;
  } catch (error) { console.error(fixture.diagnostics(), await page.locator('.notice').allTextContents(), await page.locator('.protocol-log pre').allTextContents()); throw error; }
  finally { await page.close(); await fixture.stop(passed); }
});
