import { test, expect } from '@playwright/test';
test('Harness primitive keyboard, menu, modal, hover and disclosure contracts', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:5174/test/fixtures/foundation.html');
  await expect(page).toHaveTitle('Foundation contracts');
  await page.getByRole('button', { name: 'Ordinary button' }).click();
  await expect(page.getByLabel('Submissions')).toHaveText('0');
  await page.getByRole('button', { name: 'Submit form' }).click();
  await expect(page.getByLabel('Submissions')).toHaveText('1');
  await expect(page.getByRole('button', { name: 'Disabled button' })).toBeDisabled();
  const trigger = page.getByRole('button', { name: 'Actions', exact: true });
  await trigger.click();
  await expect(page.getByRole('menuitem', { name: 'Alpha' })).toBeFocused();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('menuitem', { name: 'Charlie' })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByLabel('Selection')).toHaveText('c');
  await expect(trigger).toBeFocused();
  await trigger.click(); await page.keyboard.press('Escape'); await expect(trigger).toBeFocused();
  await page.getByRole('button', { name: 'Details', exact: true }).hover();
  await expect(page.getByText('Hover details')).toBeVisible();
  const open = page.getByRole('button', { name: 'Open dialog' });
  await open.click(); await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused();
  await page.keyboard.press('Shift+Tab'); await expect(page.getByRole('button', { name: 'Done', exact: true })).toBeFocused();
  await page.keyboard.press('Tab'); await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(open).toBeFocused();
  const disclosure = page.getByRole('button', { name: 'Expand details' });
  await disclosure.click(); await expect(disclosure).toHaveAttribute('aria-expanded', 'true');
  await expect(page.getByText('Expanded content')).toBeVisible();
  await expect(page.locator('vite-error-overlay')).toHaveCount(0); expect(errors).toEqual([]);
});
