import { chooseWorkspace } from './shell-actions';
import { expect, test } from '@playwright/test';
import { appendFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';

test('CFG3 structured source authoring, inert definitions, CAS and explicit publication', async ({ page }) => {
  const fixture = await startDogfood(); const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(fixture.endpoint);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.getByRole('dialog', { name: 'Connection', exact: true })).toHaveCount(0);
    await chooseWorkspace(page, 'Workspace A');
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
    await expect(settings.getByRole('tab', { name: 'Effective', exact: true })).toHaveAttribute('aria-selected', 'true');
    await settings.getByText('Source paths', { exact: true }).click();
    await expect(settings.getByText(fixture.settings, { exact: true })).toBeVisible();
    await expect(settings.getByText(join(fixture.directory, 'home/rustx/.agents'), { exact: true })).toBeVisible();
    await settings.screenshot({ path: test.info().outputPath('cfg3-effective.png') });
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'MCP', exact: true }).click();
    await settings.getByLabel('New MCP identity').fill('local-fixture');
    await settings.getByRole('button', { name: 'Add MCP', exact: true }).click();
    await settings.getByLabel('MCP command').fill('python3');
    await settings.getByRole('button', { name: 'Add Arguments', exact: true }).click();
    await settings.getByLabel('Arguments 1', { exact: true }).fill(fileURLToPath(new URL('./web09-mcp.py', import.meta.url)));
    await settings.getByRole('button', { name: 'Add Arguments', exact: true }).click();
    await settings.getByLabel('Arguments 2', { exact: true }).fill(join(fixture.directory, 'mcp-started'));
    await settings.getByRole('button', { name: 'Save MCP local-fixture', exact: true }).click();
    await expect(settings.getByText(/Source saved. Use Reload/)).toBeVisible();
    await expect(settings.getByText(/Pending reload/)).toBeVisible();
    expect(existsSync(join(fixture.directory, 'mcp-started'))).toBe(false);
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByText(/Configuration published:/)).toBeVisible();
    expect(existsSync(join(fixture.directory, 'mcp-started'))).toBe(false);
    await settings.getByRole('tab', { name: 'Workspace', exact: true }).click();
    await settings.getByLabel('New MCP identity').fill('local-fixture');
    await settings.getByRole('button', { name: 'Add MCP', exact: true }).click();
    await expect(settings.getByLabel('MCP command')).toHaveValue('');
    await settings.getByLabel('MCP command').fill('unused-workspace-command');
    await settings.getByRole('button', { name: 'Save MCP local-fixture', exact: true }).click();
    await expect(settings.getByText(/Source saved. Use Reload/)).toBeVisible();
    await settings.getByLabel('MCP command').fill('preserved-draft');
    appendFileSync(join(fixture.workspaceA, '.agents/mcp.toml'), '\n# external edit invalidates the draft revision\n');
    await settings.getByRole('button', { name: 'Save MCP local-fixture', exact: true }).click();
    await expect(settings.getByRole('alert')).toContainText('Conflict');
    await expect(settings.getByLabel('MCP command')).toHaveValue('preserved-draft');
    await settings.screenshot({ path: test.info().outputPath('cfg3-cas-conflict.png') });
    await settings.getByRole('button', { name: 'Use reviewed revision', exact: true }).click();
    await settings.getByRole('button', { name: 'Save MCP local-fixture', exact: true }).click();
    await expect(settings.getByText(/Source saved. Use Reload/)).toBeVisible();
    await settings.getByRole('button', { name: 'Agents', exact: true }).click();
    await settings.getByLabel('New Agent identity').fill('reviewer');
    await settings.getByRole('button', { name: 'Add Agent', exact: true }).click();
    await settings.getByLabel('Description', { exact: true }).fill('Independent review profile');
    await expect(settings.getByLabel('todo', { exact: true })).not.toBeChecked();
    await settings.getByLabel('Instructions', { exact: true }).fill('Review the requested change and report concrete findings.');
    await settings.getByLabel('read', { exact: true }).check();
    await settings.getByRole('button', { name: 'Save Agent reviewer', exact: true }).click();
    await expect(settings.getByText(/Source saved. Use Reload/)).toBeVisible();
    await expect(settings.getByRole('region', { name: 'agents inventory' }).getByRole('article').filter({ hasText: 'reviewer' })).toContainText('Valid definition');
    await settings.getByRole('heading', { name: 'Named Agents', exact: true }).scrollIntoViewIfNeeded();
    await settings.screenshot({ path: test.info().outputPath('cfg3-named-agent.png') });
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByText(/Configuration published:/)).toBeVisible();
    await expect(settings.getByText(/Pending reload/)).toHaveCount(0);
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath('cfg3-settings-mobile.png'), fullPage: true });
    await settings.getByRole('button', { name: 'Appearance', exact: true }).click();
    await settings.getByLabel('Theme', { exact: true }).selectOption('dark');
    await settings.getByRole('button', { name: 'Agents', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit Agent reviewer', exact: true }).click();
    await settings.getByRole('form', { name: 'Agent reviewer', exact: true }).evaluate(el => el.scrollIntoView({ block: 'start' }));
    await page.screenshot({ path: test.info().outputPath('cfg3-agent-mobile-dark.png') });
    expect(errors).toEqual([]);
    expect(existsSync(join(fixture.directory, 'mcp-started'))).toBe(false);
  } finally { const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
