import { expect, test } from '@playwright/test';
import { appendFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';

test('native MCP source authoring, Workspace shadowing, conflict repair and reset', async ({ page }) => {
  const fixture = await startDogfood(); const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(`${fixture.endpoint}/`);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await page.getByLabel('Choose Workspace').selectOption({ label: 'Workspace A' });
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText('attached');
    await page.getByRole('tab', { name: 'Settings', exact: true }).click();
    await page.getByRole('button', { name: 'Integrations', exact: true }).click();
    const integrations = page.getByRole('region', { name: 'Integrations', exact: true });
    await integrations.getByRole('button', { name: 'Add User MCP server' }).click();
    await integrations.getByLabel('Server identity').fill('local-fixture');
    await integrations.getByLabel('Command', { exact: true }).fill('python3');
    await integrations.getByRole('button', { name: 'Add Arguments', exact: true }).click();
    await integrations.getByLabel('Arguments 1', { exact: true }).fill(fileURLToPath(new URL('./web09-mcp.py', import.meta.url)));
    await integrations.getByRole('button', { name: 'Add Arguments', exact: true }).click();
    await integrations.getByLabel('Arguments 2', { exact: true }).fill(join(fixture.directory, 'mcp-started'));
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect(integrations.getByText('Winning source: User', { exact: true })).toBeVisible();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveCount(0);
    await integrations.getByLabel('Integration scope').selectOption('workspace');
    await integrations.getByRole('button', { name: 'Define Workspace · local-fixture' }).click();
    await integrations.getByLabel('Command', { exact: true }).fill('workspace-disabled-fixture');
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect(integrations.getByText('Shadowed User definition — editable independently')).toBeVisible();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveCount(0);
    await integrations.getByLabel('Integration scope').selectOption('user');
    await integrations.getByRole('button', { name: 'Edit User · local-fixture' }).click();
    await integrations.getByLabel('Command', { exact: true }).fill('edited-shadowed-user');
    appendFileSync(fixture.settings, '\n# deterministic external CAS change\n');
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('Conflict');
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveValue('edited-shadowed-user');
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveCount(0);
    await expect(integrations.getByText('Winning source: Workspace', { exact: true })).toBeVisible();
    await integrations.getByLabel('Integration scope').selectOption('workspace');
    await integrations.getByRole('button', { name: 'Edit Workspace · local-fixture' }).click();
    await integrations.getByRole('button', { name: 'Delete authored MCP entry' }).click();
    await expect(integrations.getByText('Winning source: User', { exact: true })).toBeVisible();
    await page.screenshot({ path: 'test-results/web09-integrations.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/web09-integrations-mobile.png', fullPage: true });
    expect(existsSync(join(fixture.directory, 'mcp-started'))).toBe(false);
    expect(errors).toEqual([]);
  } finally { const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
