import { test, expect } from '@playwright/test';
test('MCP scope shows only definitions owned by the selected scope', async ({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>localStorage.setItem('rustx-locale-v1','en'));
 await page.goto(`http://127.0.0.1:${process.env.RUSTX_E2E_FIXTURE_PORT??5174}/test/fixtures/settings.html?scenario=mcp-scope`);
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByRole('tab',{name:'MCP servers',exact:true}).click();
 await expect(page.getByRole('listitem',{name:'exa',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Configuration scope'}).click();
 await page.getByRole('menuitem',{name:'Workspace A',exact:true}).click();
 await expect(page.getByText('No MCP servers installed',{exact:true})).toBeVisible();
 await expect(page.getByRole('listitem',{name:'exa',exact:true})).toHaveCount(0);
 await expect(page.getByText('Inherited from user',{exact:true})).toHaveCount(0);
 await expect(page.locator('[data-mcp-page] [class*="total"]')).toHaveText('MCP 0');
 await page.screenshot({path:'/tmp/rustx-mcp-workspace-scope.png'});
 await page.getByRole('button',{name:'Configuration scope'}).click();
 await page.getByRole('menuitem',{name:'User (global)',exact:true}).click();
 await expect(page.getByRole('listitem',{name:'exa',exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
