import { chooseWorkspace, connectionAction } from './shell-actions';
import { expect, test } from '@playwright/test';
import { readFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';
import { wireProbe } from './wire-probe';

test('CFG3 committed write and reload response loss reconstructs native state without replay', async ({ page }) => {
  const fixture = await startDogfood(); const wire = await wireProbe(page);
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(fixture.endpoint);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await chooseWorkspace(page, 'Workspace A');
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.getByLabel('Message', { exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
    const writes = () => wire.requests.filter(request => request.method === 'configuration/sourceWrite');
    const reconnect = async () => {
      await expect(page.locator('.status strong')).toHaveText('stale');
      await connectionAction(page, 'Reconnect');
      await expect(page.locator('.status strong')).toHaveText('connected');
      await settings.getByRole('button', { name: 'Read current sources', exact: true }).click();
    };
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit Model fixture/console-model', exact: true }).click();
    await settings.getByLabel('Context window').fill('250000');
    appendFileSync(fixture.settings, '\n# external revision before save\n');
    await settings.getByRole('button', { name: 'Save Model fixture/console-model', exact: true }).click();
    await expect(settings.getByRole('alert')).toContainText('Conflict');
    await expect(settings.getByLabel('Context window')).toHaveValue('250000');
    expect(readFileSync(fixture.settings, 'utf8')).not.toContain('250000');
    expect(writes()).toHaveLength(1);
    await settings.getByRole('button', { name: 'Use reviewed revision', exact: true }).click();
    wire.loseNext('configuration/sourceWrite');
    await settings.getByRole('button', { name: 'Save Model fixture/console-model', exact: true }).click();
    await expect.poll(wire.lost).toBe(1);
    expect(readFileSync(fixture.settings, 'utf8')).toContain('250000');
    await reconnect();
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit Model fixture/console-model', exact: true }).click();
    await expect(settings.getByLabel('Context window')).toHaveValue('250000');
    expect(writes()).toHaveLength(2);
    await settings.getByRole('button', { name: 'MCP', exact: true }).click();
    await settings.getByLabel('New MCP identity').fill('loss-fixture');
    await settings.getByRole('button', { name: 'Add MCP', exact: true }).click();
    await settings.getByLabel('MCP command', { exact: true }).fill('inert-fixture');
    wire.loseNext('configuration/sourceWrite');
    await settings.getByRole('button', { name: 'Save MCP loss-fixture', exact: true }).click();
    await expect.poll(wire.lost).toBe(2);
    expect(readFileSync(join(fixture.directory, 'home/rustx/.agents/mcp.toml'), 'utf8')).toContain('inert-fixture');
    await reconnect();
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'MCP', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit MCP loss-fixture', exact: true }).click();
    await expect(settings.getByLabel('MCP command', { exact: true })).toHaveValue('inert-fixture');
    expect(writes()).toHaveLength(3);
    wire.loseNext('configuration/reload');
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect.poll(wire.lost).toBe(3); await reconnect();
    await expect(settings.getByText(/Pending reload/)).toHaveCount(0);
    expect(wire.requests.filter(request => request.method === 'configuration/reload')).toHaveLength(1);
    expect(writes()).toHaveLength(3);
    // Remounting a different Session reconstructs its own authoritative source scope.
    await settings.getByLabel('MCP command', { exact: true }).fill('unsaved-draft');
    await chooseWorkspace(page, 'Workspace B');
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText(fixture.workspaceB);
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'MCP', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit MCP loss-fixture', exact: true }).click();
    await expect(settings.getByLabel('MCP command', { exact: true })).toHaveValue('inert-fixture');
    expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toMatch(/250000|loss-fixture|unsaved-draft/);
  } finally { await page.close(); const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
