import { expect, test } from '@playwright/test';
import { readFileSync, appendFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';
import { wireProbe } from './wire-probe';

test('real committed Provider and MCP response loss rereads without replay; CAS preserves draft', async ({ page }) => {
  const fixture = await startDogfood();
  const wire = await wireProbe(page);
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(fixture.endpoint);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await page.getByLabel('Choose Workspace').selectOption({ label: 'Workspace A' });
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.getByLabel('Message', { exact: true })).toBeEnabled();
    await page.getByRole('tab', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('region', { name: 'Settings', exact: true });
    const catalog = join(dirname(fixture.settings), 'models.toml');
    await settings.getByLabel('Context window').first().fill('250000');
    appendFileSync(catalog, '\n# external revision before save\n');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('alert')).toContainText('Conflict');
    await expect(settings.getByLabel('Context window').first()).toHaveValue('250000');
    expect(readFileSync(catalog, 'utf8')).not.toContain('250000');
    const writes = () => wire.requests.filter(request => request.method === 'settings/sourcesWrite');
    expect(writes()).toHaveLength(1);
    wire.loseNext('settings/sourcesWrite');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect.poll(wire.lost).toBe(1);
    await expect(page.locator('.status strong')).toHaveText('stale');
    expect(readFileSync(catalog, 'utf8')).toContain('250000');
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(settings.getByLabel('Context window').first()).toHaveValue('250000');
    expect(writes()).toHaveLength(2);
    await settings.getByRole('button', { name: 'Integrations', exact: true }).click();
    const integrations = page.getByRole('region', { name: 'Integrations', exact: true });
    await integrations.getByRole('button', { name: 'Add User MCP server' }).click();
    await integrations.getByLabel('Server identity').fill('loss-fixture');
    await integrations.getByLabel('Command', { exact: true }).fill('inert-disabled-fixture');
    wire.loseNext('settings/sourcesWrite');
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect.poll(wire.lost).toBe(2);
    await expect(page.locator('.status strong')).toHaveText('stale');
    expect(readFileSync(fixture.settings, 'utf8')).toContain('inert-disabled-fixture');
    await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(integrations.getByText('Definition winner: User', { exact: true })).toBeVisible();
    expect(writes()).toHaveLength(3);
    await integrations.getByRole('button', { name: 'Edit User · loss-fixture' }).click();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveValue('inert-disabled-fixture');
    expect(wire.requests.filter(request => request.method === 'settings/sourcesRead').length).toBeGreaterThan(3);
    await integrations.getByLabel('Command', { exact: true }).fill('unsaved-user-draft');
    await expect(integrations.getByLabel('Integration scope')).toBeDisabled();
    await integrations.getByRole('button', { name: 'Discard MCP draft' }).click();
    await integrations.getByLabel('Integration scope').selectOption('workspace');
    await integrations.getByRole('button', { name: 'Define Workspace · loss-fixture' }).click();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveValue('');
    await integrations.getByRole('combobox', { name: 'Transport', exact: true }).selectOption('http');
    await integrations.getByLabel('URL', { exact: true }).fill('http://127.0.0.1:1/mcp');
    await integrations.getByRole('combobox', { name: 'Activation', exact: true }).selectOption('disabled');
    await integrations.getByRole('button', { name: 'Save MCP', exact: true }).click();
    await expect(integrations.getByText('Definition winner: Workspace', { exact: true })).toBeVisible();
    await integrations.getByRole('button', { name: 'Edit Workspace · loss-fixture' }).click();
    await expect(integrations.getByLabel('URL', { exact: true })).toHaveValue('http://127.0.0.1:1/mcp');
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveValue('');
    await expect(integrations.getByRole('combobox', { name: 'Activation', exact: true })).toHaveValue('disabled');
    await integrations.getByLabel('URL', { exact: true }).fill('http://unsaved-workspace-draft/mcp');
    await settings.getByRole('button', { name: 'Provider / Models', exact: true }).click();
    await settings.getByLabel('Endpoint · fixture').fill('http://unsaved-provider-draft/v1');
    // A different Workspace/Session remount cannot inherit either editor draft.
    await page.getByLabel('Choose Workspace').selectOption({ label: 'Workspace B' });
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText(fixture.workspaceB);
    await page.getByRole('tab', { name: 'Settings', exact: true }).click();
    await expect(settings.getByLabel('Endpoint · fixture')).toHaveValue(`${fixture.providerUrl}/v1`);
    await settings.getByRole('button', { name: 'Integrations', exact: true }).click();
    await expect(integrations.getByLabel('URL', { exact: true })).toHaveCount(0);
    await expect(integrations.getByText('Definition winner: User', { exact: true })).toBeVisible();
    await integrations.getByRole('button', { name: 'Edit User · loss-fixture' }).click();
    await expect(integrations.getByLabel('Command', { exact: true })).toHaveValue('inert-disabled-fixture');
    await expect(integrations.getByLabel('URL', { exact: true })).toHaveValue('');

    expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toMatch(/250000|loss-fixture|inert-disabled/);
  } finally { await page.close(); const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
