import { connectRemote } from './shell-actions';
import { chooseWorkspace } from './shell-actions';
import { expect, test } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';

test('CFG3 atomic Provider and Model editing, Root selections, Save and reload failure', async ({ page }) => {
  const fixture = await startDogfood();
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await connectRemote(page, fixture.endpoint, fixture.token);
    await expect(page.getByLabel('Transport token')).toHaveCount(0);
    await chooseWorkspace(page, 'Workspace A');
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
    await settings.getByRole('button', { name: 'Overview', exact: true }).click();
    const saved = async () => { await expect(settings.getByText(/Source saved. Use Reload/)).toBeVisible(); };
    await settings.getByRole('tab', { name: 'User', exact: true }).click();
    await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
    await settings.getByLabel('New Provider identity').fill('acceptance');
    await settings.getByRole('button', { name: 'Add Provider', exact: true }).click();
    await settings.getByLabel('Endpoint', { exact: true }).fill('http://127.0.0.1:1/v1');
    await settings.getByLabel('Environment variable', { exact: true }).fill('RUSTX_CONSOLE_FIXTURE_KEY');
    await settings.getByRole('button', { name: 'Save Provider acceptance', exact: true }).click(); await saved();
    await settings.getByRole('heading', { name: 'Providers & Models', exact: true }).scrollIntoViewIfNeeded();
    await settings.screenshot({ path: test.info().outputPath('cfg3-user-provider-pending.png') });
    await settings.getByRole('button', { name: 'Back to catalog' }).click();
    await settings.getByLabel('New Model identity').fill('independent');
    await settings.getByRole('button', { name: 'Add Model', exact: true }).click();
    await settings.getByLabel('Wire model identity').fill('wire-a');
    await settings.getByLabel('Provider identity', { exact: true }).fill('acceptance');
    await settings.getByRole('button', { name: 'Save Model independent', exact: true }).click(); await saved();
    await settings.getByRole('heading', { name: 'Providers & Models', exact: true }).scrollIntoViewIfNeeded();
    await settings.screenshot({ path: test.info().outputPath('cfg3-user-model.png') });
    await settings.getByRole('tab', { name: 'Workspace', exact: true }).click();
    await settings.getByLabel('New Model identity').fill('independent');
    await settings.getByRole('button', { name: 'Add Model', exact: true }).click();
    await expect(settings.getByLabel('Wire model identity')).toHaveValue('');
    await settings.getByLabel('Wire model identity').fill('wire-workspace');
    await settings.getByLabel('Provider identity', { exact: true }).fill('acceptance');
    await settings.getByRole('button', { name: 'Save Model independent', exact: true }).click(); await saved();
    await settings.getByRole('button', { name: 'Back to catalog' }).click();
    await settings.getByLabel('New Provider identity').fill('acceptance');
    await settings.getByRole('button', { name: 'Add Provider', exact: true }).click();
    await expect(settings.getByLabel('Endpoint', { exact: true })).toHaveValue('');
    await expect(settings.getByLabel('Credential source')).not.toContainText('Retain');
    await settings.getByLabel('Endpoint', { exact: true }).fill('http://127.0.0.1:2/v1');
    await settings.getByLabel('Environment variable', { exact: true }).fill('RUSTX_CONSOLE_FIXTURE_KEY');
    await settings.getByRole('button', { name: 'Save Provider acceptance', exact: true }).click(); await saved();
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByText(/Configuration published:/)).toBeVisible();
    await settings.getByRole('tab', { name: 'Effective', exact: true }).click();
    await expect(settings.getByRole('article').filter({ hasText: 'wire-workspace' })).toContainText('workspace:');
    await expect(settings.getByRole('article').filter({ hasText: 'http://127.0.0.1:2/v1' })).toContainText('workspace:');
    await expect(settings.getByRole('button', { name: /Save / })).toHaveCount(0);
    await settings.screenshot({ path: test.info().outputPath('cfg3-effective-provenance.png') });
    await settings.getByRole('tab', { name: 'Workspace', exact: true }).click();
    await settings.getByRole('button', { name: 'Tools', exact: true }).click();
    await expect(settings.getByLabel('read', { exact: true })).not.toBeChecked();
    await settings.getByLabel('read', { exact: true }).check();
    await settings.getByRole('button', { name: 'Save Native Tools', exact: true }).click(); await saved();
    // Source families share exact/all/none selection without activating definitions.
    for (const [family, id] of [['mcp', 'absent-mcp'], ['python', 'absent-python']]) {
      await settings.getByLabel('Source family').selectOption(family);
      await settings.getByLabel('Source identity', { exact: true }).fill(id);
      await settings.getByRole('button', { name: 'Add source selection', exact: true }).click();
      const name = family === 'python' ? `python:${id}` : id;
      const source = settings.getByRole('group', { name: `Source ${name}`, exact: true });
      await source.getByRole('combobox', { name: 'Selection', exact: true }).selectOption('all');
      await source.getByRole('combobox', { name: 'Selection', exact: true }).selectOption('exact');
      await source.getByRole('textbox', { name: `${name} identities 1`, exact: true }).fill('inspect');
      await source.getByRole('combobox', { name: 'Selection', exact: true }).selectOption('none');
      await source.getByRole('button', { name: `Save Source ${name}`, exact: true }).click(); await saved();
    }
    await settings.getByRole('button', { name: 'Skill access', exact: true }).click();
    await expect(settings).toContainText('not filesystem access');
    await expect(settings).toContainText(`${fixture.workspaceA}/.agents/skills`);
    await settings.getByRole('combobox', { name: 'Selection', exact: true }).selectOption('all');
    await settings.getByRole('button', { name: 'Save Skill visibility', exact: true }).click(); await saved();
    await settings.getByRole('button', { name: 'Plugins', exact: true }).click();
    await expect(settings.getByLabel('Enable todo', { exact: true })).not.toBeChecked();
    await settings.getByRole('switch', { name: 'Enable todo', exact: true }).click();
    await settings.getByRole('button', { name: 'Save todo Plugin', exact: true }).click(); await saved();
    await settings.getByRole('heading', { name: 'Plugins', exact: true }).scrollIntoViewIfNeeded();
    await settings.screenshot({ path: test.info().outputPath('cfg3-native-plugins.png') });
    await settings.getByRole('button', { name: 'Agents & Workflows', exact: true }).click();
    await expect(settings.getByRole('group', { name: 'agents', exact: true }).getByRole('textbox')).toHaveCount(0);
    await settings.getByRole('button', { name: 'Save Agent allowlist', exact: true }).click(); await saved();
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByText(/Configuration published:/)).toBeVisible();
    const authored = readFileSync(fixture.settings, 'utf8');
    writeFileSync(fixture.settings, 'invalid = [');
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByRole('alert')).toContainText('remains authoritative');
    await expect(settings.getByRole('alert')).toContainText('TOML error');
    await settings.screenshot({ path: test.info().outputPath('cfg3-reload-failed.png') });
    writeFileSync(fixture.settings, authored);
    await settings.getByRole('button', { name: 'Reload', exact: true }).click();
    await expect(settings.getByText(/Configuration published:/)).toBeVisible();
    // Independent removal of each authored identity is revision fenced too.
    await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
    await settings.getByRole('button', { name: 'Edit Model independent', exact: true }).click();
    await settings.getByRole('button', { name: 'Remove Model independent', exact: true }).click(); await saved();
    await settings.getByRole('button', { name: 'Back to catalog' }).click();
    await settings.getByRole('button', { name: 'Edit Provider acceptance', exact: true }).click();
    await settings.getByRole('button', { name: 'Remove Provider acceptance', exact: true }).click(); await saved();
    expect(errors).toEqual([]);
  } finally { const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
