import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';

test('native Settings source save, reset, catalog edit and responsive projection', async ({ page }) => {
  const fixture = await startDogfood();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await routeWorkspaceHost(page, fixture); await page.goto('/');
    await page.getByLabel('WebSocket endpoint').fill(`${fixture.endpoint}/`);
    await page.getByLabel('Transport token').fill(fixture.token);
    await page.getByRole('button', { name: 'Connect', exact: true }).click();
    await expect(page.locator('.status strong')).toHaveText('connected');
    await page.getByLabel('Choose Workspace').selectOption({ label: 'Workspace A' });
    await page.getByRole('button', { name: 'Create Session', exact: true }).click();
    await expect(page.locator('.session-toolbar small')).toContainText('attached');
    await page.getByRole('tab', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('region', { name: 'Settings', exact: true });
    await expect(settings.getByRole('heading', { name: 'Settings · Provider / Models' })).toBeVisible();
    await expect(settings.getByLabel('User model', { exact: true })).toHaveValue('fixture/console-model');
    const workspace = settings.getByRole('group', { name: 'Workspace', exact: true });
    await workspace.getByText('Partial source request policy', { exact: true }).click();
    await workspace.getByRole('combobox', { name: 'Workspace output policy', exact: true }).selectOption('limit');
    await workspace.getByRole('spinbutton', { name: 'Workspace output limit', exact: true }).fill('1024');
    await workspace.getByRole('button', { name: 'Save Workspace', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await expect(workspace.getByLabel('Workspace model', { exact: true })).toHaveValue('');
    await expect(settings.getByRole('region', { name: 'Prospective effective request', exact: true })).toContainText('1024');
    await expect(settings.getByRole('region', { name: 'Runtime effective request', exact: true })).toContainText('4096');
    await settings.getByLabel('Workspace model', { exact: true }).selectOption('fixture/second-model');
    await settings.getByRole('button', { name: 'Save Workspace', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await expect(settings.locator('dd').first()).toHaveText('fixture/second-model');
    await settings.getByRole('button', { name: 'Reset Workspace', exact: true }).click();
    await settings.getByRole('button', { name: 'Save Workspace', exact: true }).click();
    await expect(settings.locator('dd').first()).toHaveText('fixture/console-model');
    await settings.getByLabel('Context window').first().fill('256000');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(settings.getByLabel('Context window').first()).toHaveValue('256000');
    // Complete the User-only structured catalog lifecycle, with no provider IO.
    await settings.getByLabel('New Provider identity').fill('acceptance');
    await settings.getByRole('button', { name: 'Add Provider', exact: true }).click();
    const provider = settings.locator('article').filter({ has: page.getByRole('heading', { name: 'acceptance', exact: true }) });
    await provider.getByLabel('Endpoint · acceptance').fill('http://127.0.0.1:1/v1');
    await provider.getByLabel('Credential environment reference · acceptance').fill('RUSTX_CONSOLE_FIXTURE_KEY');
    await provider.getByRole('button', { name: 'Add model to acceptance' }).click();
    await provider.getByLabel('Model identity', { exact: true }).fill('explicit-model');
    await provider.getByLabel('Context window').fill('64000');
    await provider.getByLabel('Maximum output tokens').fill('1024');
    await provider.getByRole('checkbox', { name: 'text', exact: true }).nth(0).check();
    await provider.getByRole('checkbox', { name: 'text', exact: true }).nth(1).check();
    const catalogPath = join(dirname(fixture.settings), 'models.toml');
    const beforeInvalid = readFileSync(catalogPath, 'utf8');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('alert')).toContainText('invalid_params');
    expect(readFileSync(catalogPath, 'utf8')).toBe(beforeInvalid);
    await provider.getByText('Request defaults and protocol compatibility', { exact: true }).click();
    await provider.getByLabel('Chat reasoning replay').selectOption('omit');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(provider.getByLabel('Model identity', { exact: true })).toHaveValue('explicit-model');
    await provider.getByLabel('Endpoint · acceptance').fill('http://127.0.0.1:2/v1');
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(provider.getByLabel('Endpoint · acceptance')).toHaveValue('http://127.0.0.1:2/v1');
    await provider.getByRole('button', { name: 'Delete Provider acceptance' }).click();
    await settings.getByRole('button', { name: 'Save User catalog', exact: true }).click();
    await expect(settings.getByRole('status')).toContainText('Source committed');
    await settings.getByRole('button', { name: 'Reload / discard draft' }).click();
    await expect(provider).toHaveCount(0);
    await expect(page.locator('vite-error-overlay')).toHaveCount(0);
    await page.screenshot({ path: 'test-results/settings-desktop.png', fullPage: true });
    await settings.getByText('User Provider / model catalog', { exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: 'test-results/settings-catalog.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await settings.scrollIntoViewIfNeeded();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/settings-mobile.png', fullPage: true });
    expect(errors).toEqual([]);
  } finally { const report = await fixture.stop(false); expect(report.requestCount).toBe(0); }
});
