import { expect, test } from '@playwright/test';
import { closeSettings, openWorkspaceSettings } from './shell-actions';
test('native Settings reference cards, inventories, keyboard scopes and narrow theme', async ({ page }) => {
 const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
 await page.clock.setFixedTime(new Date('2026-09-18T12:00:00Z')); await page.emulateMedia({ reducedMotion: 'reduce' });
 await page.goto('http://127.0.0.1:5174/test/fixtures/settings.html');
 await expect(page).toHaveTitle('rustX native Settings reference');
 await page.getByRole('button', { name: 'Settings', exact: true }).click();
 const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
 await expect(settings.getByRole('button', { name: 'Overview', exact: true })).toHaveAttribute('aria-current', 'page');
 await expect(settings.getByText(/Revision: user-1/)).toBeVisible();
 await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
 await expect(settings).toHaveScreenshot('settings-user-catalog-light.png');
 await closeSettings(page);
 await openWorkspaceSettings(page, 'Workspace A');
 await settings.getByRole('button', { name: 'Providers & Models', exact: true }).click();
 await settings.getByRole('button', { name: 'Edit Model main' }).click();
 await expect(settings).toHaveScreenshot('settings-model-editor-light.png');
 await settings.getByRole('button', { name: 'Plugins', exact: true }).click(); await expect(settings.getByRole('switch', { name: 'Enable goal' })).toBeChecked();
 await expect(settings).toHaveScreenshot('settings-plugins-light.png');
 await settings.getByRole('button', { name: 'Skills', exact: true }).click();
 await expect(settings.getByText('Invalid definition')).toBeVisible(); await expect(settings).toHaveScreenshot('settings-inventory-light.png');
 await settings.getByRole('button', { name: 'Appearance', exact: true }).click(); await settings.getByLabel('Theme', { exact: true }).selectOption('dark');
 await settings.getByRole('button', { name: 'General', exact: true }).click(); await expect(settings.getByLabel('Agent identity')).toBeVisible();
 await expect(settings).toHaveScreenshot('settings-general-dark.png');
 await page.setViewportSize({ width: 390, height: 844 });
 await settings.getByRole('button', { name: 'Agents', exact: true }).click(); await settings.getByRole('button', { name: 'Edit Agent reviewer' }).click();
 await settings.getByRole('form', { name: 'Agent reviewer' }).evaluate(el => el.scrollIntoView({ block: 'start' }));
 await expect(settings.getByLabel('Description', { exact: true })).toBeVisible();
 await expect(page).toHaveScreenshot('settings-agent-narrow-dark.png');
 expect(await settings.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
 await page.keyboard.press('Escape'); await expect(settings).toHaveCount(0);
 // The global entry restores focus to its own trigger; the Workspace entry is
 // opened from the exact Workspace object action instead.
 await page.getByRole('button', { name: 'Settings', exact: true }).click();
 await expect(settings).toBeVisible();
 await page.keyboard.press('Escape'); await expect(settings).toHaveCount(0);
 await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeFocused();
 await expect(page.locator('vite-error-overlay')).toHaveCount(0); expect(errors).toEqual([]);
});
