import { test, expect } from '@playwright/test';

for (const width of [1440, 390]) test(`context reading survives streaming at ${width}`, async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto(`http://127.0.0.1:${process.env.RUSTX_E2E_FIXTURE_PORT ?? 5174}/test/fixtures/startup.html?existing`);
  await expect(page).toHaveTitle('rustX startup ownership fixture');
  await expect(page).toHaveURL(/test\/fixtures\/startup\.html\?existing/);
  await expect(page.locator('vite-error-overlay')).toHaveCount(0);
  await page.evaluate(() => { const f = (window as any).startupFixture; f.allow('session/summary'); f.resumeCatalog(); });
  await page.locator('button[data-session-id=A]').click();
  await page.evaluate(() => (window as any).startupFixture.release('session/attach'));
  await page.setViewportSize({ width, height: 900 });
  if (width < 600) await page.getByRole('button', { name: 'Collapse Sidebar', exact: true }).click();
  await page.evaluate(() => (window as any).startupFixture.contextReading(25000));
  const ring = page.getByRole('button', { name: '25% of context used', exact: true });
  await expect(ring).toBeVisible();
  await page.evaluate(() => (window as any).startupFixture.contextReading(25000, true));
  await expect(ring).toBeVisible();
  await ring.click();
  await expect(page.getByRole('dialog', { name: 'of context used', exact: true })).toContainText('25K / 100K');
  await page.keyboard.press('Escape');
  await page.screenshot({ path: `/tmp/rustx-streaming-context-${width}.png` });
  await page.evaluate(() => (window as any).startupFixture.contextReading(30000));
  await expect(page.getByRole('button', { name: '30% of context used', exact: true })).toBeVisible();
  await page.evaluate(() => (window as any).startupFixture.contextReading(null));
  await expect(page.getByRole('button', { name: /\d+% of context used/ })).toHaveCount(0);
  expect(errors).toEqual([]);
});
