import { test, expect } from '@playwright/test';
const origin=`http://127.0.0.1:${process.env.RUSTX_E2E_FIXTURE_PORT ?? 5174}`;
test('document registry defaults to rendered Markdown and retains explicit source choices',async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel=page.locator('[data-workbench]');
  await panel.getByRole('button',{name:/Workspace files/}).click();
  await panel.getByRole('button',{name:'docs',exact:true}).click();
  await panel.getByRole('button',{name:'guide.md',exact:true}).click();
  await expect(panel.getByRole('heading',{name:'Rendered document'})).toBeVisible();
  await expect(panel.locator('[data-document-frontmatter]')).toContainText('Sidebar documentation');
  await expect(panel.getByRole('cell',{name:'Ready',exact:true})).toBeVisible();
  await expect.poll(()=>panel.getByRole('img',{name:'diagram',exact:true}).evaluate((el:HTMLImageElement)=>el.naturalWidth)).toBe(800);
  await page.screenshot({path:info.outputPath('markdown-rendered.png')});
  await panel.getByRole('button',{name:'View as',exact:true}).click();
  await page.getByRole('menuitem',{name:'Code',exact:true}).click();
  await expect(panel.locator('[data-workbench-file] code')).toContainText('# Rendered document');
  await panel.getByRole('tab',{name:/Files/}).click();
  await panel.getByRole('button',{name:'guide.md',exact:true}).click();
  await expect(panel.locator('[data-workbench-file] code')).toBeVisible();
  await panel.getByRole('button',{name:'View as',exact:true}).click();
  await page.getByRole('menuitem',{name:'Markdown',exact:true}).click();
  await panel.getByRole('link',{name:'Read source'}).click();
  await expect(panel.locator('[data-workbench-file="src/test.py"] pre')).toContainText('def greet');
  expect(errors).toEqual([]);
});
test('HTML, image, PDF and spreadsheets use specialized viewers',async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();const panel=page.locator('[data-workbench]');
  await panel.getByRole('button',{name:/Workspace files/}).click();await panel.getByRole('button',{name:'docs',exact:true}).click();
  const open=async(name:string)=>{await panel.getByRole('tab',{name:/Files/}).click();await panel.getByRole('button',{name,exact:true}).click();};
  await open('page.html');await expect(panel.frameLocator('iframe').getByRole('heading',{name:'HTML document'})).toBeVisible();
  expect(await panel.frameLocator('iframe').getByRole('heading').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(200, 0, 0)');
  await open('diagram.svg');await expect(panel.locator('[data-document-zoom-frame] img')).toBeVisible();
  await page.screenshot({path:info.outputPath('image-preview.png')});
  await open('sample.pdf');await expect(panel.locator('canvas')).toBeVisible();
  await expect(panel.getByRole('button',{name:'Next',exact:true})).toBeVisible();
  await open('table.csv');await expect(panel.locator('[data-excel-preview]')).toBeVisible();
  await expect(panel.locator('.fortune-sheet-container')).toBeVisible();
  await open('sample.xlsx');await expect(panel.locator('.fortune-sheet-container')).toBeVisible();
  await page.screenshot({path:info.outputPath('spreadsheet-preview.png')});
  expect(errors).toEqual([]);
});
test('source dockkit floats, docks, restores and collapses the last content tab',async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${origin}/test/fixtures/workbench.html`);await page.locator('[data-preview-toggle]').click();
  const panel=page.locator('[data-workbench]');
  await panel.getByRole('button',{name:/Workspace files/}).click();await panel.getByRole('button',{name:'docs',exact:true}).click();
  await panel.getByRole('button',{name:'guide.md',exact:true}).click();
  const chip=panel.getByRole('tab',{name:/guide.md/});const box=(await chip.boundingBox())!;
  await page.mouse.move(box.x+15,box.y+14);await page.mouse.down();await page.mouse.move(600,220,{steps:12});await page.mouse.up();
  const floating=panel.locator('[data-dockkit-float]');await expect(floating).toBeVisible();
  await expect(floating.getByRole('heading',{name:'Rendered document'})).toBeVisible();
  await page.locator('[data-preview-toggle]').click();
  await expect(floating.getByRole('heading',{name:'Rendered document'})).toBeVisible();
  await page.screenshot({path:info.outputPath('floating-markdown.png')});
  await floating.getByRole('button',{name:'Dock panel',exact:true}).click();
  await expect(floating).toHaveCount(0);
  await page.locator('[data-preview-toggle]').click();
  await expect(panel.getByRole('heading',{name:'Rendered document'})).toBeVisible();
  await page.reload();await page.locator('[data-preview-toggle]').click();
  await expect(panel.getByRole('heading',{name:'Rendered document'})).toBeVisible();
  await panel.getByRole('tab',{name:/guide.md/}).getByRole('button',{name:'Close tab'}).click();
  await panel.getByRole('tab',{name:/Files/}).getByRole('button',{name:'Close tab'}).click();
  await expect(panel).toBeHidden();
  await page.locator('[data-preview-toggle]').click();await expect(panel.getByRole('button',{name:/Workspace files/})).toBeVisible();
  expect(errors).toEqual([]);
});

test('interactive HTML packs local assets and executes inside an opaque sandbox',async({page})=>{
  await page.addInitScript(()=>{ if(localStorage.getItem('rustx-html-interactive-v1')===null)localStorage.setItem('rustx-html-interactive-v1','true'); });
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel=page.locator('[data-workbench]');
  await panel.getByRole('button',{name:/Workspace files/}).click();
  await panel.getByRole('button',{name:'docs',exact:true}).click();
  await panel.getByRole('button',{name:'interactive.html',exact:true}).click();
  const frame=panel.frameLocator('iframe');
  await expect(frame.getByRole('button',{name:'Count 0'})).toBeVisible();
  await frame.getByRole('button',{name:'Count 0'}).click();
  await expect(frame.getByRole('button',{name:'Count 1'})).toBeVisible();
  await expect(frame.locator('#boundary')).toHaveText('isolated');
  expect(await frame.getByRole('button').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(12, 34, 56)');
  await expect(panel.locator('iframe')).toHaveAttribute('sandbox','allow-scripts');
  await page.evaluate(()=>localStorage.setItem('rustx-html-interactive-v1','false'));
  await page.reload();await page.locator('[data-preview-toggle]').click();
  await expect(panel.locator('iframe')).toHaveAttribute('sandbox','');
  await frame.getByRole('button',{name:'Count 0'}).click();
  await expect(frame.getByRole('button',{name:'Count 0'})).toBeVisible();
  await expect(frame.locator('#boundary')).toHaveText('');
});

test('workspace HTML stays static until the user explicitly opts into scripts',async({page})=>{
  const dependencies:string[]=[];
  page.on('request',request=>{const body=request.postData();if(body&&/counter\.js|counter\.css/.test(body))dependencies.push(body);});
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();const panel=page.locator('[data-workbench]');
  await panel.getByRole('button',{name:/Workspace files/}).click();
  await panel.getByRole('button',{name:'docs',exact:true}).click();
  await panel.getByRole('button',{name:'interactive.html',exact:true}).click();
  await expect(panel.locator('iframe')).toHaveAttribute('sandbox','');
  const frame=panel.frameLocator('iframe');
  await frame.getByRole('button',{name:'Count 0'}).click();
  await expect(frame.getByRole('button',{name:'Count 0'})).toBeVisible();
  await expect(frame.locator('#boundary')).toHaveText('');
  expect(dependencies).toEqual([]);
});
