import { connectRemote } from './shell-actions';
import { closeSessionView } from './shell-actions';
import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { AppServerHost } from '../../../tui/src/app-server/host';
import { startDogfood } from './dogfood-server';
import { routeWorkspaceHost } from './workspace-host';

test('two isolated Product Hosts/processes, cold Sessions and responsive Workspace navigation', async ({ page }) => {
  const a = await startDogfood(), b = await startDogfood();
  const remoteA = await AppServerHost.connectRemote({ endpoint: a.endpoint, token: a.token });
  const remoteB = await AppServerHost.connectRemote({ endpoint: b.endpoint, token: b.token });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  try {
    // Unselected malformed resources warn without preventing unrelated composition.
    writeFileSync(join(a.workspaceA, 'rustx.toml'), '[agent]\ninstructions = "Workspace guidance"\n');
    for (const kind of ['agents', 'skills', 'workflows', 'tools']) {
      mkdirSync(join(a.workspaceA, '.agents', kind), { recursive: true });
      writeFileSync(join(a.workspaceA, '.agents', kind, 'invalid.toml'), 'must never activate');
    }
    writeFileSync(join(a.workspaceA, 'AGENTS.md'), 'WORKSPACE_PROJECT_INSTRUCTIONS');
    const wa = (await a.workspaceHost.host.listWorkspaces()).workspaces[0];
    const wb = (await b.workspaceHost.host.listWorkspaces()).workspaces[0];
    await expect(a.workspaceHost.host.resolveWorkspace(wb.id, a.endpoint)).rejects.toThrow('Unknown');
    await expect(a.workspaceHost.host.resolveWorkspace(wa.id, b.endpoint)).rejects.toThrow('different rustX process');
    const cwd = await a.workspaceHost.host.resolveWorkspace(wa.id, a.endpoint);
    const created = await remoteA.createSession(cwd);
    const id = created.session.id;
    const read = () => remoteA.client.call('session/settings', { session_id: id }, 'settings');
    const original = await read(); expect(original.settings.cwd).toBe(a.workspaceA);
    await expect(remoteB.readSession(id)).rejects.toThrow();
    const listed = await remoteA.client.call('session/list', { offset: 0, limit: 32 }, 'sessions');
    expect(listed.sessions.find(row => row.id === id)?.cwd).toBe(a.workspaceA);
    expect(listed).not.toHaveProperty('residencies');
    expect((await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.loaded).toBe(0);
    const outside = join(a.directory, 'outside-host-roots'); mkdirSync(outside);
    const denied = await remoteA.createSession({ cwd: outside });
    const deniedBefore = await remoteA.readSettings(denied.session.id);
    await page.addInitScript(({ endpoint, id }) => localStorage.setItem('rustx-console-view-v2', JSON.stringify({ endpoint, openViews: [id] })), { endpoint: a.endpoint, id: denied.session.id });
    await routeWorkspaceHost(page, a); await page.goto('/'); await expect(page).toHaveTitle(/rustX/);
    await connectRemote(page, a.endpoint, a.token);
    await expect(page.locator(`button[data-session-id="${id}"]`)).toBeVisible();
    await page.getByText("Sessions outside registered Workspaces", { exact: true }).click();
    await expect(page.locator(`button[data-session-id="${denied.session.id}"]`)).toBeVisible();
    await page.locator(`button[data-session-id="${denied.session.id}"]`).click();
    await expect(page.getByRole('alert')).toContainText('not authorized');
    expect((await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.loaded).toBe(0);
    expect(await remoteA.readSettings(denied.session.id)).toEqual(deniedBefore);
    await page.getByRole('button', { name: 'Select Workspace Workspace A' }).click();
    await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeEnabled();
    expect((await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.loaded).toBe(0);
    await page.locator(`button[data-session-id="${id}"]`).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled();
    await expect(page.getByText(/Untrusted project source/)).toHaveCount(0);
    expect(await read()).toEqual(original);
    const resident = (await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot;
    expect(resident.loaded).toBe(1);
    await closeSessionView(page, id);
    await expect.poll(async () => (await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.external_attachments).toBe(0);
    const attached = await remoteA.client.call('session/attach', { session_id: id }, 'attached');
    await remoteA.client.call('configuration/reconcile', { target: { kind: 'user' } }, 'configuration_application');
    const refreshed = await remoteA.client.call('session/snapshot', { target: attached.target }, 'snapshot');
    expect(refreshed.snapshot.resources?.revision).toBe(attached.snapshot.resources?.revision);
    await remoteA.client.call('session/detach', { target: attached.target }, 'detached');
    await page.locator(`button[data-session-id="${id}"]`).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'View options' }).click();
    await page.getByRole('menuitem', { name: 'Flat view' }).click();
    await expect(page.locator(`button[data-session-id="${id}"]`)).toBeVisible();
    await page.getByRole('button', { name: 'View options' }).click();
    await page.getByRole('menuitem', { name: 'Grouped view' }).click();
    await page.getByRole('button', { name: 'Select Workspace Workspace A' }).focus();
    await page.getByRole('button', { name: 'Toggle Workspace A' }).click();
    await expect(page.locator(`button[data-session-id="${id}"]`)).toHaveCount(0);
    await page.getByRole('button', { name: 'Select Workspace Workspace A' }).focus();
    await page.getByRole('button', { name: 'Toggle Workspace A' }).click();
    await page.screenshot({ path: 'test-results/workspaces-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Expand Sidebar' }).click();
    await page.getByRole('button', { name: 'Select Workspace Workspace A' }).scrollIntoViewIfNeeded();
    await expect(page.locator(`button[data-session-id="${id}"]`)).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/workspaces-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: 'Select Workspace Workspace B' }).click();
    expect((await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.loaded).toBe(1);
    await a.workspaceHost.host.renameWorkspace(wa.id, 'Renamed by Host');
    await a.workspaceHost.host.reorderWorkspace(wa.id);
    expect(await read()).toEqual(original);
    await a.workspaceHost.host.removeWorkspace(wa.id);
    await page.getByRole('button', { name: 'View options' }).click();
    await page.getByRole('menuitem', { name: 'Refresh list' }).click();
    await expect(page.getByRole('button', { name: 'Select Workspace Workspace A', exact: true })).toHaveCount(0);
    await page.getByText('Sessions outside registered Workspaces', { exact: true }).click();
    await expect(page.locator(`button[data-session-id="${id}"]`)).toBeVisible();
    expect(await read()).toEqual(original);
    expect((await remoteA.client.call('server/diagnostics', {}, 'diagnostics')).snapshot.loaded).toBe(1);
    await page.locator(`button[data-session-id="${id}"]`).click();
    await closeSessionView(page, id);
    await page.locator(`button[data-session-id="${id}"]`).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled();
    await expect(page.locator('[aria-label^="Select Workspace"][aria-current="page"]')).toHaveCount(0);
    expect((await a.workspaceHost.host.listWorkspaces()).workspaces.some(row => row.id === wa.id)).toBe(false);
    expect(await remoteA.readSettings(denied.session.id)).toEqual(deniedBefore);
    expect((await b.workspaceHost.host.listWorkspaces()).workspaces[0]).toEqual(wb);
    expect((await remoteB.listSessions()).sessions).toHaveLength(0);
    const other = await remoteB.createSession(await b.workspaceHost.host.resolveWorkspace(wb.id, b.endpoint));
    expect(other.session.id).toMatch(/^ses_[0-9a-f-]+$/);
    expect((await remoteB.readSettings(other.session.id)).settings.cwd).toBe(b.workspaceA);
    expect((await read()).settings.cwd).toBe(a.workspaceA);
    expect(await a.workspaceHost.host.classifyLocations([b.workspaceA], a.endpoint)).toEqual([{ authorized: false }]);
    expect(existsSync(join(a.directory, 'state', 'rustx', 'trust'))).toBe(false);
    expect(readFileSync(join(a.workspaceA, 'rustx.toml'), 'utf8')).toContain('Workspace guidance');
    expect(errors).toEqual([]);
  } finally { await remoteA.shutdown(); await remoteB.shutdown(); await a.stop(false); await b.stop(false); }
});
