import { test, expect } from '@playwright/test';
const origin = `http://127.0.0.1:${process.env.RUSTX_E2E_FIXTURE_PORT ?? 5174}`;
test('workspace panel browses real files and runs a real PTY, including collapse and fullscreen', async ({ page }, info) => {
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  const toggle = page.locator('[data-preview-toggle]');
  await toggle.click();
  const panel = page.locator('[data-workbench]');
  await expect(panel).toBeVisible();
  await expect(panel.getByRole('button', { name: /New terminal/ })).toBeEnabled();
  await expect.poll(async () => (await panel.boundingBox())!.x + (await panel.boundingBox())!.width).toBeLessThanOrEqual(1440);
  await page.screenshot({path: info.outputPath('workbench-start.png')});
  await panel.getByRole('button', { name: /Workspace files/ }).click();
  await panel.getByRole('button', { name: 'src', exact: true }).click();
  await panel.getByRole('button', { name: 'hello.txt' }).click();
  await expect(panel.locator('pre')).toHaveText('Workspace preview works.');
  await panel.getByRole('button', { name: 'New tab', exact: true }).click();
  await panel.getByRole('button', { name: /New terminal/ }).click();
  await expect(panel.locator('.xterm')).toBeVisible();
  await panel.locator('.xterm-helper-textarea').fill("printf 'RUSTX_%s\\n' TERMINAL");
  await panel.locator('.xterm-helper-textarea').press('Enter');
  // xterm's renderer paints to the browser DOM, independent of transport echoes.
  await expect.poll(async () => panel.locator('.xterm-rows').textContent()).toContain('RUSTX_TERMINAL');
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click();
  await expect(page.locator('[data-sidebar-right-panel]')).toHaveAttribute('data-sidebar-right-panel','fullscreen');
  await page.getByRole('button', { name: 'Restore', exact: true }).click();
  await toggle.click(); await expect(panel).toBeHidden(); await toggle.click(); await expect(panel.locator('.xterm')).toBeVisible();
  await expect.poll(async () => panel.locator('.xterm-rows').textContent()).toContain('RUSTX_TERMINAL');
  await expect.poll(async () => (await panel.boundingBox())!.x + (await panel.boundingBox())!.width).toBeLessThanOrEqual(1440);
  await page.screenshot({path: info.outputPath('workbench-terminal.png')});
  await panel.getByRole('button', { name: 'Close terminal 1' }).click();
  await expect(panel.getByRole('button', { name: 'Close terminal 1' })).toHaveCount(0);
});

test('Chinese narrow workspace panel opens as a full-width page and closes', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.addInitScript(() => localStorage.setItem('rustx-locale-v1', 'zh'));
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel = page.locator('[data-workbench]');
  await expect(panel.getByRole('button', { name: /工作区文件/ })).toBeVisible();
  await expect(panel.getByRole('button', { name: /新建终端/ })).toBeEnabled();
  await expect(page.locator('[data-sidebar-right-panel]')).toHaveAttribute('data-sidebar-right-panel', 'fullscreen');
  await page.screenshot({ path: info.outputPath('guide-zh-narrow.png') });
  await page.locator('aside[data-sidebar-right-open]').getByRole('button', { name: '切换工作区面板' }).click();
  await expect(panel).toBeHidden();
});

test('Harness guide geometry, single-row tabs, shell menu, split and terminal theme follow the source', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel = page.locator('[data-workbench]');
  const files = panel.getByRole('button', { name: /Workspace files/ });
  await expect(files).toBeEnabled();
  await expect.poll(() => files.evaluate(el => getComputedStyle(el).width)).toBe('380px');
  expect(await files.evaluate(el => ({ padding: getComputedStyle(el).padding, fontWeight: getComputedStyle(el).fontWeight, radius: getComputedStyle(el).borderRadius }))).toEqual({ padding: '14px 20px', fontWeight: '400', radius: '20px' });
  await expect(panel.locator('header')).toHaveCount(1);
  expect(await panel.locator('header').evaluate(el => el.getBoundingClientRect().height)).toBe(38);
  await panel.getByRole('button', { name: 'Terminal shell', exact: true }).click();
  await page.getByRole('menuitem', { name: 'sh', exact: true }).click();
  await expect(panel.getByRole('tab', { name: 'sh', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(panel.locator('.xterm')).toBeVisible();
  await expect.poll(() => panel.locator('.xterm').evaluate(el => getComputedStyle(el.parentElement!).backgroundColor)).toBe('rgb(255, 255, 255)');
  await page.screenshot({ path: info.outputPath('terminal-light.png') });
  await page.evaluate(() => document.body.setAttribute('data-ds-dark-theme', ''));
  await expect.poll(() => panel.locator('.xterm-viewport').evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe('rgb(255, 255, 255)');
  await page.screenshot({ path: info.outputPath('terminal-dark.png') });
  await panel.getByRole('button', { name: 'New tab', exact: true }).click();
  await expect(panel.getByRole('tab', { name: 'Start', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(panel.locator('header')).toHaveCount(1);
  await panel.getByRole('tab', { name: 'Start', exact: true }).press('ArrowLeft');
  await expect(panel.getByRole('tab', { name: 'sh', exact: true })).toBeFocused();
  await panel.getByRole('button', { name: 'Fullscreen', exact: true }).click();
  await panel.getByRole('button', { name: 'Split pane', exact: true }).click();
  await expect(panel.locator('[data-workbench-pane]')).toHaveCount(2);
  await expect(panel.getByRole('button', { name: 'Restore', exact: true })).toHaveCount(1);
  const separator = panel.getByRole('separator'); await separator.focus(); await separator.press('ArrowRight'); await expect(separator).toHaveAttribute('aria-valuenow', '52');
  await panel.getByRole('button', { name: 'Merge panes', exact: true }).first().click();
  await expect(panel.locator('[data-workbench-pane]')).toHaveCount(1);
  await panel.getByRole('tab', { name: 'sh', exact: true }).click();
  await panel.getByRole('button', { name: 'Close terminal 1' }).click();
  await page.keyboard.press('Control+Backquote');
  await expect(panel.locator('.xterm')).toBeVisible();
  await page.keyboard.press('Control+Alt+p');
  await expect(panel.getByRole('region', { name: 'Workspace files', exact: true })).toBeVisible();
  await panel.getByRole('tab', { name: 'sh', exact: true }).click();
  await panel.getByRole('button', { name: 'Close terminal 1' }).click();
  expect(errors).toEqual([]);
});

test('Chinese guide keeps upstream light and dark artwork and typography', async ({ page }, info) => {
  await page.addInitScript(() => localStorage.setItem('rustx-locale-v1', 'zh'));
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel = page.locator('[data-workbench]');
  await expect(panel.getByRole('button', { name: '新建终端', exact: true })).toBeEnabled();
  await expect.poll(async () => (await panel.boundingBox())!.x + (await panel.boundingBox())!.width).toBeLessThanOrEqual(1440);
  await panel.screenshot({ path: info.outputPath('guide-zh-light.png') });
  await page.evaluate(() => document.body.setAttribute('data-ds-dark-theme', ''));
  await expect.poll(() => panel.evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe('rgb(255, 255, 255)');
  await panel.screenshot({ path: info.outputPath('guide-zh-dark.png') });
});

test('file tree and source tabs preserve their own view state and use Harness toolbar geometry', async ({ page, context }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto(`${origin}/test/fixtures/workbench.html`);
  await page.locator('[data-preview-toggle]').click();
  const panel = page.locator('[data-workbench]');
  await panel.getByRole('button', { name: /Workspace files/ }).click();
  const tree = panel.locator('[data-workbench-files]');
  await expect(tree.locator('[data-path-label]')).toHaveAttribute('title', /rustx-workbench-browser-/);
  await tree.getByRole('button', { name: 'src', exact: true }).click();
  await expect(tree.getByRole('button', { name: 'test.py', exact: true })).toBeVisible();
  expect(await tree.locator('li[data-files-path^="src/"] > button').allTextContents()).toEqual(['file2.txt', 'file10.txt', 'hello.txt', 'test.py']);
  expect(await tree.locator('[data-path-label]').evaluate(el => el.parentElement!.getBoundingClientRect().height)).toBe(38);
  await page.screenshot({ path: info.outputPath('files-tree-light.png') });
  await tree.getByRole('button', { name: 'test.py', exact: true }).click();
  const file = panel.locator('[data-workbench-file="src/test.py"]');
  await expect(panel.getByRole('tab', { name: 'test.py', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(file.locator('[data-path-label]')).toHaveAttribute('title', /\/src\/test.py$/);
  await expect(file.locator('[data-line-numbers]')).toBeVisible();
  await expect(file.locator('[data-code-block-banner]')).toContainText('python');
  await expect(file.locator('pre.shiki')).toBeVisible();
  await file.getByRole('button', { name: 'Wrap lines', exact: true }).click();
  await expect(file.getByRole('button', { name: 'Wrap lines', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await file.getByRole('button', { name: 'View as', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Text', exact: true }).click();
  await expect(file.locator('[data-code-block-banner]')).toHaveCount(0);
  await file.getByRole('button', { name: 'View as', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Code', exact: true }).click();
  await file.getByRole('button', { name: 'Copy', exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('def greet(name):');
  await page.screenshot({ path: info.outputPath('file-python-light.png') });
  await panel.getByRole('tab', { name: 'Files', exact: true }).click();
  await expect(tree.getByRole('button', { name: 'src', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await tree.getByRole('button', { name: 'test.py', exact: true }).click();
  await expect(panel.getByRole('tab', { name: 'test.py', exact: true })).toHaveCount(1);
  await expect(file.getByRole('button', { name: 'Wrap lines', exact: true })).toHaveAttribute('aria-pressed', 'true');
  // The path came from the native test Host. Change the real file, then explicitly reload it.
  const { writeFileSync } = await import('node:fs');
  const cwd = await file.locator('[data-path-label]').getAttribute('title');
  expect(cwd).toContain('/rustx-workbench-browser-');
  writeFileSync(cwd!, 'print("refreshed")\n');
  await file.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(file.locator('pre')).toHaveText('print("refreshed")');
  await page.evaluate(() => document.body.setAttribute('data-ds-dark-theme', ''));
  await page.screenshot({ path: info.outputPath('file-python-dark.png') });
  await panel.getByRole('tab', { name: 'test.py', exact: true }).locator('..').getByRole('button', { name: 'Close tab' }).click();
  await expect(tree.getByRole('button', { name: 'test.py', exact: true })).toBeVisible();
  await tree.getByRole('button', { name: 'src', exact: true }).click();
  await expect(tree.getByRole('button', { name: 'test.py', exact: true })).toHaveCount(0);
  await tree.getByRole('button', { name: 'src', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await tree.getByRole('button', { name: 'test.py', exact: true }).click();
  await expect(file).toBeVisible();
  expect(await file.evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('file-python-narrow.png') });
  await page.evaluate(() => localStorage.setItem('rustx-locale-v1', 'zh'));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.reload(); await page.locator('[data-preview-toggle]').click();
  await panel.getByRole('button', { name: /工作区文件/ }).click();
  await panel.getByRole('button', { name: 'src', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'test.py', exact: true })).toBeVisible();
  await panel.screenshot({ path: info.outputPath('files-tree-zh.png') });
  await panel.getByRole('button', { name: 'test.py', exact: true }).click();
  await expect(panel.getByRole('button', { name: '查看方式' })).toHaveText('代码');
  await expect(file.locator('pre.shiki')).toBeVisible();
  await panel.screenshot({ path: info.outputPath('file-python-zh.png') });
  expect(errors).toEqual([]);
});
