import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it } from 'vitest';
import type { CompletedProcessView, RuntimeClientTranscriptEntry } from '../../protocol/app-server/v21';
import { AgentTranscript } from '../src/app/agent/AgentTranscript';
import { turnProcesses } from '../src/bindings/turn-process';
import { snapshot } from './fixture';
afterEach(cleanup);
const process = (attempt = 'a', final = 'final'): CompletedProcessView => ({ origin: { conversation_id: 'c', attempt_id: attempt, closing_message_id: final }, final_message_id: final });
const row = (id: string, owner?: CompletedProcessView, reasoning = false): RuntimeClientTranscriptEntry => ({ cursor: id, completed_process: owner, item: { type: 'message', message: { role: 'assistant', id, content: [...(reasoning ? [{ type: 'reasoning' as const, text: `Thought ${id}` }] : []), { type: 'text', text: `Answer ${id}` }] } } });
const user: RuntimeClientTranscriptEntry = { cursor: 'u', item: { type: 'message', message: { role: 'user', id: 'u', source: 'human', content: [{ type: 'text', text: 'steering' }] } } };
it('folds only native completed membership across steering and interleaved Attempts, leaving final and live work visible', () => {
  const entries = [row('first', process(), true), user, row('live', undefined, true), row('second', process(), true), row('final', process(), true)];
  const before = JSON.stringify(entries);
  const ui = render(<AgentTranscript snapshot={{ ...snapshot(), transcript: { entries } }}/>);
  const folded = screen.getByRole('button', { name: '2 messages' });
  expect(folded.getAttribute('aria-expanded')).toBe('false');
  expect(screen.getByText('Answer first').closest('[hidden]')).not.toBeNull();
  for (const text of ['Answer final', 'Answer live', 'steering']) expect(screen.getByText(text).closest('[hidden]')).toBeNull();
  fireEvent.click(folded);
  expect(screen.getByText('Answer first').closest('[hidden]')).toBeNull();
  for (const disclosure of screen.getAllByRole('button', { name: /^Reasoning/ })) fireEvent.click(disclosure);
  expect(ui.container.querySelectorAll('[data-markdown-variant="compact"]').length).toBeGreaterThanOrEqual(3);
  expect(screen.getByText('Answer final').closest('[data-markdown-variant]')?.getAttribute('data-markdown-variant')).toBe('normal');
  fireEvent.click(folded);
  expect(JSON.stringify(entries)).toBe(before);
});
it('pagination and retry origins preserve disclosure identity without merging turns', () => {
  const a = process(), b = process('retry', 'retry-final');
  const page = [row('late', a), row('final', a)];
  const key = turnProcesses(page).membership.get('late');
  const larger = turnProcesses([row('early', a), ...page, row('retry-middle', b), row('retry-final', b)]);
  expect(larger.membership.get('early')).toBe(key);
  expect(larger.membership.get('late')).toBe(key);
  expect(larger.membership.get('retry-middle')).not.toBe(key);
  expect(larger.groups.size).toBe(2);
  expect(larger.membership.has('final')).toBe(false);
  expect(larger.membership.has('retry-final')).toBe(false);
});
it.each([0, 1, 3])('counts %i exact native tool occurrences, not result bodies or display names', count => {
  const entry = row('calls', process());
  entry.tool_calls = Array.from({ length: count }, (_, block_index) => ({ message_id: 'calls', block_index, call_id: String(block_index), tool_id: 'bash', name: 'anything', state: { type: 'assembled', arguments: '{}' } }));
  const groups = turnProcesses([entry, row('final', process())]);
  expect([...groups.groups.values()][0].tools).toBe(count);
});
it('a page beginning at a suppressed Tool result retains a reachable process disclosure and final answer', () => {
  const result: RuntimeClientTranscriptEntry = { cursor: 'result', completed_process: process(), item: { type: 'message', message: { role: 'tool', id: 'result', occurrence: { assistant_message_id: 'earlier-call', block_index: 0 }, tool_call_id: 'call', tool_id: 'bash', result: { status: { type: 'success' }, duration_ms: 1, content: [] } } } };
  render(<AgentTranscript snapshot={{ ...snapshot(), transcript: { entries: [result, row('final', process())] } }}/>);
  expect(screen.getByRole('button', { name: 'Thought for a while' })).toBeTruthy();
  expect(screen.getByText('Answer final').closest('[hidden]')).toBeNull();
});
it('folds a status by exact native Attempt without moving its inbound anchor or hiding steering', () => {
  const entries = [user, row('middle', process()), row('final', process())];
  render(<AgentTranscript snapshot={{ ...snapshot(), conversation_id: 'c', transcript: { entries }, statuses: [{ attempt_id: 'a', turn: 1, status_message_id: 'status', opportunities: { fresh_inbound: { target_message_id: 'u' } }, sections: [], rendered: 'native context' }] }}/>);
  const note = screen.getByRole('note', { name: 'Agent Status', hidden: true });
  const anchor = note.closest('[data-chat-anchor-key]');
  expect(note.closest('[hidden]')).not.toBeNull();
  expect(screen.getByText('steering').closest('[hidden]')).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: '1 message' }));
  expect(note.closest('[hidden]')).toBeNull();
  expect(note.closest('[data-chat-anchor-key]')).toBe(anchor);
});
