import { useState } from 'react';
import type { RuntimeLayer, SourceScope, SourceToolSelection, ModelLayer, AgentSkillSelection, AgentStatusExtensionDocument, AgentProjectInstructionsDocument } from '../../../../protocol/app-server/v18';
import { Button } from '../../presentation/primitives/Button';
import { ModelSelectionFields, StatusPluginFields } from './AgentEditor';
import { CheckboxList, Toggle, Names, nativeTools, Selection, TextField, UnitForm, type SaveSource } from './controls';
import { reachableIdentities } from './projection';

export type RootSection = 'root-model' | 'root-tools' | 'root-skills' | 'root-plugins' | 'root-agents';
export function RootEditor({ document, resolved, scope, revision, save, section, models, skillRoots }: { document: RuntimeLayer; resolved?: RuntimeLayer | null; scope: SourceScope; revision: string; save: SaveSource; section: RootSection; models: string[]; skillRoots: string[] }) {
  const agent = document.agent;
  const [source, setSource] = useState(''), [added, setAdded] = useState<string[]>([]), [family, setFamily] = useState('mcp');
  return <section aria-label="Root Agent">
    {section === 'root-model' && <><UnitForm<ModelLayer> title="Root model" authored={agent?.model ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'root_model', authored } })}>{(value, change) => <ModelSelectionFields value={value} change={change} models={models} />}</UnitForm>
      <UnitForm<AgentProjectInstructionsDocument> title="Project guidance" authored={agent?.agents_md ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'project_guidance', authored } })}>{(value, change) => <><label><input type="checkbox" checked={value.inherit ?? true} onChange={e => change({ ...value, inherit: e.target.checked })} />Include project guidance</label><Names label="Guidance files" value={value.files ?? []} change={files => change({ ...value, files })} /></>}</UnitForm></>}
    {section === 'root-tools' && <><UnitForm<string[]> title="Native Tools" authored={agent?.tools?.builtin ?? undefined} blank={[]} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'native_tools', authored } })}>{(value, change) => <CheckboxList label="Explicit whitelist" values={nativeTools} selected={value} change={change} />}</UnitForm>
      <p>Absent Root Native Tool selection grants no Tools. Source selections are atomic per MCP server or Python package.</p>
      {[...new Set([...reachableIdentities(scope, agent?.tools?.sources, resolved?.agent?.tools?.sources), ...added])].map(id => <UnitForm<SourceToolSelection> key={id} title={`Source ${id}`} authored={agent?.tools?.sources?.[id] ?? undefined} blank={[]} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'source_tools', id, authored } })}>{(value, change) => <Selection label={id} value={value} change={change} />}</UnitForm>)}
      <label>Source family<select value={family} onChange={e => setFamily(e.target.value)}><option value="mcp">MCP</option><option value="python">Managed Python</option></select></label><TextField label="Source identity" value={source} change={setSource} /><Button disabled={!source} onClick={() => { setAdded(current => [...current, family === 'python' ? `python:${source}` : source]); setSource(''); }}>Add source selection</Button>
    </>}
    {section === 'root-skills' && <><p>Skill selection controls prompt visibility, not filesystem access. Tools retain ordinary read behavior and progressive disclosure.</p><dl><dt>User Skill root</dt><dd>{skillRoots[0]}</dd><dt>Workspace Skill root</dt><dd>{skillRoots[1]}</dd></dl><UnitForm<AgentSkillSelection> title="Skill visibility" authored={agent?.skills ?? undefined} blank={[]} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'skills', authored } })}>{(value, change) => <Selection label="Visible Skills" value={value} change={change} />}</UnitForm></>}
    {section === 'root-plugins' && <><p>Closed native Plugins default off. Each Workspace Plugin replaces the same User Plugin as a whole. Current Todo and Goal state belongs to the Conversation.</p>{(['todo', 'goal'] as const).map(unit => <UnitForm<{ enabled?: boolean }> key={unit} title={`${unit} Plugin`} authored={agent?.plugins?.[unit] ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit, authored } })}>{(value, change) => <Toggle label={`Enable ${unit}`} checked={value.enabled ?? false} change={enabled => change({ enabled })} />}</UnitForm>)}<UnitForm<AgentStatusExtensionDocument> title="Agent Status Plugin" authored={agent?.plugins?.agent_status ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'agent_status', authored } })}>{(value, change) => <StatusPluginFields value={value} change={change} />}</UnitForm></>}
    {section === 'root-agents' && <><p>Existence of a resource grants no Root authority. Named Agents own independent profiles; Root Tool and Plugin selections do not impose a ceiling on them.</p>{(['agents', 'workflows'] as const).map(unit => <UnitForm<string[]> key={unit} title={unit === 'agents' ? 'Agent allowlist' : 'Workflow allowlist'} authored={agent?.[unit] ?? undefined} blank={[]} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit, authored } })}>{(value, change) => <Names label={unit} value={value} change={change} />}</UnitForm>)}</>}
  </section>;
}
