import { useState } from 'react';
import type { RuntimeLayer, SourceScope, ContextLayer, TimeoutLayer, ToolDeadlineLayer, NativePolicyOverrideDocument, NativeTool, ApprovalMode, AppServerPolicy } from '../../../../protocol/app-server/v18';
import { Button } from '../../presentation/primitives/Button';
import { TextField, UnitForm, policyTools, type SaveSource } from './controls';
import { changeBehavior, changeBehaviorLabel } from './projection';

export function PolicyFields({ value, change }: { value: NativePolicyOverrideDocument; change: (value: NativePolicyOverrideDocument) => void }) {
  return <>{(['execution', 'concurrency', 'approval'] as const).map(key => <label key={key}>{key}<select value={value[key] ?? ''} onChange={e => change({ ...value, [key]: e.target.value || undefined })}><option value="">Domain default</option>{(key === 'execution' ? ['foreground_only', 'background_only', 'model_selectable'] : key === 'concurrency' ? ['sequential', 'parallel'] : ['never', 'always']).map(option => <option key={option}>{option}</option>)}</select></label>)}</>;
}
export function RuntimeEditor({ document, scope, revision, save, policyOnly, processPolicyImpacts }: { document: RuntimeLayer; scope: SourceScope; revision: string; save: SaveSource; policyOnly: boolean; processPolicyImpacts?: Record<string, 'hot' | 'restart'> }) {
  const [mcp, setMcp] = useState(''), [selectedMcp, selectMcp] = useState(''), [env, setEnv] = useState(''), [selectedEnv, selectEnv] = useState('');
  if (policyOnly) return <section><h3>Tool Policies</h3><p>Global invocation policy governs execution, concurrency, and approval independently of Agent capability selection. Each policy is replaced as one complete object.</p>{policyTools.map(name => <UnitForm<NativePolicyOverrideDocument> key={name} title={`${name} policy`} authored={document.native_tools?.[name as NativeTool] ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'native_policy', id: name as NativeTool, authored } })}>{(value, change) => <PolicyFields value={value} change={change} />}</UnitForm>)}
    <label>MCP policy identity<input list="mcp-policy-identities" value={mcp} onChange={e => setMcp(e.target.value)} /></label><datalist id="mcp-policy-identities">{Object.keys(document.mcp_tool_policies ?? {}).map(id => <option key={id}>{id}</option>)}</datalist><Button disabled={!mcp} onClick={() => selectMcp(mcp)}>Edit MCP policy</Button>
    {selectedMcp && <UnitForm<NativePolicyOverrideDocument> key={selectedMcp} title={`MCP policy ${selectedMcp}`} authored={document.mcp_tool_policies?.[selectedMcp] ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'mcp_policy', id: selectedMcp, authored } })}>{(value, change) => <PolicyFields value={value} change={change} />}</UnitForm>}
  </section>;
  return <section><h3>Runtime · General</h3>
    <UnitForm<string> title="Root identity" authored={document.agent_id ?? undefined} blank="" revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'agent_identity', authored } })}>{(value, change) => <TextField label="Agent identity" value={value} change={change} />}</UnitForm>
    <UnitForm<string> title="Root description" authored={document.agent?.description ?? undefined} blank="" revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'description', authored } })}>{(value, change) => <TextField label="Root description" value={value} change={change} />}</UnitForm>
    <UnitForm<string> title="Root instructions" authored={document.agent?.instructions ?? undefined} blank="" revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'instructions', authored } })}>{(value, change) => <label>Instructions<textarea value={value} onChange={e => change(e.target.value)} /></label>}</UnitForm>
    {scope === 'workspace' && <p>App Server process policy is User-only. Native application state reports which changes have applied.</p>}
    <UnitForm<ApprovalMode> title="Approval mode" authored={document.approval_mode ?? undefined} blank="policy" revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'approval', authored } })}>{(value, change) => <label>Approval mode<select value={value} onChange={e => change(e.target.value as ApprovalMode)}><option value="policy">Policy</option><option value="full_access">Full access</option></select></label>}</UnitForm>
    <UnitForm<ContextLayer> title="Context policy" authored={document.context ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'context', authored } })}>{(value, change) => <>{(['reserve_tokens', 'keep_recent_tokens'] as const).map(key => <TextField key={key} label={key} value={value[key]} change={next => change({ ...value, [key]: next || null })} />)}<label>Summary output<select value={value.summary_output_cap?.mode ?? ''} onChange={e => change({ ...value, summary_output_cap: e.target.value === 'limit' ? { mode: 'limit', tokens: 2048 } : e.target.value === 'model_limit' ? { mode: 'model_limit' } : null })}><option value="">Domain default</option><option value="model_limit">Model limit</option><option value="limit">Explicit token limit</option></select></label>{value.summary_output_cap?.mode === 'limit' && <label>Summary token limit<input type="number" min="1" value={value.summary_output_cap.tokens} onChange={e => change({ ...value, summary_output_cap: { mode: 'limit', tokens: Number(e.target.value) } })} /></label>}</>}</UnitForm>
    <UnitForm<TimeoutLayer> title="Model timeout" authored={document.model_timeout_policy ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'model_timeout', authored } })}>{(value, change) => <>{(['response_start_timeout_ms', 'stream_idle_timeout_ms'] as const).map(key => <TextField key={key} label={key} value={value[key]} change={next => change({ ...value, [key]: next || null })} />)}</>}</UnitForm>
    <UnitForm<ToolDeadlineLayer> title="Tool deadline" authored={document.tool_deadline_policy ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'tool_deadline', authored } })}>{(value, change) => <><TextField label="Hard deadline (ms)" value={value.hard_deadline_ms} change={hard_deadline_ms => change({ ...value, hard_deadline_ms: hard_deadline_ms || null })} /><label>Idle liveness<select value={value.idle_liveness_ms?.mode ?? ''} onChange={e => change({ ...value, idle_liveness_ms: e.target.value === 'window' ? { mode: 'window', milliseconds: '30000' } : e.target.value === 'disabled' ? { mode: 'disabled' } : null })}><option value="">Domain default</option><option value="disabled">Disabled</option><option value="window">Idle window</option></select></label>{value.idle_liveness_ms?.mode === 'window' && <TextField label="Idle window (ms)" value={value.idle_liveness_ms.milliseconds} change={milliseconds => change({ ...value, idle_liveness_ms: { mode: 'window', milliseconds } })} />}</>}</UnitForm>
    <UnitForm<{ max_concurrent?: number | null }> title="Child capacity" authored={document.subagents ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'capacity', authored } })}>{(value, change) => <label>Maximum concurrent children<input type="number" min="1" value={value.max_concurrent ?? ''} onChange={e => change({ max_concurrent: e.target.value ? Number(e.target.value) : null })} /></label>}</UnitForm>
    <TextField label="Environment variable identity" value={env} change={setEnv} /><Button disabled={!env} onClick={() => selectEnv(env)}>Edit environment variable</Button>
    <ul>{Object.keys(document.environment ?? {}).map(name => <li key={name}><Button onClick={() => selectEnv(name)}>{name}</Button></li>)}</ul>
    {selectedEnv && <UnitForm<string> key={selectedEnv} title={`Environment ${selectedEnv}`} authored={document.environment?.[selectedEnv] ?? undefined} blank="" revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'environment', name: selectedEnv, authored } })}>{(value, change) => <TextField label="Literal Tool environment value" value={value} change={change} />}</UnitForm>}
    {scope === 'user' && <><p>Native change behavior: {Object.keys(processPolicyImpacts ?? {}).map(name => `${name}: ${changeBehaviorLabel(changeBehavior(processPolicyImpacts, name))}`).join('; ')}</p><UnitForm<AppServerPolicy> title="App Server policy" authored={document.app_server ?? undefined} blank={{}} revision={revision} save={save} mutation={authored => ({ kind: 'config', mutation: { unit: 'app_server', authored } })}>{(value, change) => <>{(['max_resident_runtimes', 'max_connections', 'max_external_attachments', 'idle_grace_ms', 'shutdown_deadline_ms'] as const).map(key => <label key={key}>{key}<input type="number" min="1" value={value[key] ?? ''} onChange={e => change({ ...value, [key]: e.target.value ? Number(e.target.value) : undefined })} /></label>)}</>}</UnitForm></>}
  </section>;
}
