//! The provider-neutral summary service.
//!
//! A compaction summary is generated by a [`ContextSummarizer`] that the
//! context runtime owns. Since M7.5 (Issue #54) the request boundary is
//! derived directly from the **selected span of complete canonical active
//! messages** of the current Conversation Surface. There is no separate
//! "previous checkpoint summary" truth: when a previous compaction summary
//! is still active, it is simply one canonical
//! `User(Runtime / CompactionSummary)` message inside the selected span.
//!
//! Summary generation is agent-execution activity only: it never recurses
//! into `AgentExecution`, never exposes tools, never carries Agent Status or
//! the Skill catalog, never carries provider continuation, and never commits
//! anything to the Message Ledger.

use futures_util::StreamExt;
use futures_util::future::BoxFuture;
use serde::{Deserialize, Serialize};

use crate::context::error::{ContextError, ContextErrorKind};
use crate::message::content::TextBlock;
use crate::message::types::{
    InboundKind, MessageBlock, UserContentBlock, UserMessageBlock, UserSource,
};
use crate::model::event::ModelEvent;
use crate::model::invocation::ResolvedModelInvocation;
use crate::model::types::ModelRequest;
use crate::runtime::cancellation::CancellationSignal;
use crate::runtime::identity::MessageId;

/// One summarizer request.
///
/// The request carries exactly the complete canonical messages of the
/// selected Surface span, in Surface order. Nothing is flattened, nothing is
/// partial, and no hidden previous-summary channel exists beside it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SummaryRequest {
    /// The selected span of complete canonical active messages, in Surface
    /// order. A still-active previous compaction summary appears here as an
    /// ordinary `User(Runtime / CompactionSummary)` message.
    pub retired: Vec<MessageBlock>,
}

impl SummaryRequest {
    /// Whether this request covers at least one canonical message.
    #[must_use]
    pub fn advances_coverage(&self) -> bool {
        !self.retired.is_empty()
    }
}

/// The summary service.
pub trait ContextSummarizer: Send + Sync {
    /// Generates the textual summary of one request.
    ///
    /// The returned future is owned by the summarizer and must observe
    /// `cancellation`; cancellation may abort the summary.
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: CancellationSignal,
    ) -> BoxFuture<'_, Result<String, ContextError>>;
}

/// The production summarizer backed by an attempt's resolved summary model
/// invocation.
///
/// The invocation is the attempt's frozen summary resolution — the primary
/// invocation itself in `session` mode, or the separately resolved explicit
/// summary invocation — optionally narrowed by the context plane's summary
/// output safety cap. There is deliberately no independent "summary provider
/// config" system and no production path that injects an unrelated
/// summarizer beside the attempt's model.
///
/// The summary request is a canonical one-off `ModelRequest`: no tools, no
/// Agent Status, no Skill catalog, no continuation, and a deterministic
/// instruction plus the serialized request input. A refusal (with or without
/// a `RefusalDelta`), a tool request, an invalid stream, a model failure, or
/// an empty/whitespace-only output is a compaction failure, and any provider
/// continuation emitted by the one-off request is discarded: summary
/// activity never contaminates the attempt's continuation or usage state.
pub struct ModelBackedSummarizer {
    invocation: ResolvedModelInvocation,
}

impl ModelBackedSummarizer {
    /// Creates a summarizer over one resolved summary invocation.
    #[must_use]
    pub const fn new(invocation: ResolvedModelInvocation) -> Self {
        Self { invocation }
    }

    /// The resolved invocation this summarizer sends with.
    #[must_use]
    pub const fn invocation(&self) -> &ResolvedModelInvocation {
        &self.invocation
    }

    /// The deterministic summary instruction text.
    #[must_use]
    pub const fn instruction() -> &'static str {
        "Summarize the following conversation history for continuation. \
         Preserve all decisions, tool outcomes, and open threads; produce a \
         compact factual summary. Output only the summary text."
    }

    /// Serializes the request input deterministically for the model.
    ///
    /// The serialization is canonical JSON over runtime-owned types and is
    /// a pure function of the request.
    ///
    /// # Panics
    ///
    /// Panics only if the canonical request input fails to serialize, which
    /// is unreachable for the canonical runtime-owned types.
    #[must_use]
    pub fn serialize_input(request: &SummaryRequest) -> String {
        serde_json::to_string(request).expect("summary request serializes")
    }
}

impl ContextSummarizer for ModelBackedSummarizer {
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: CancellationSignal,
    ) -> BoxFuture<'_, Result<String, ContextError>> {
        Box::pin(async move {
            let input = ModelBackedSummarizer::serialize_input(&request);
            let instruction = format!("{}\n\n{}", ModelBackedSummarizer::instruction(), input);
            let messages = vec![MessageBlock::User(UserMessageBlock {
                id: MessageId::new("summary-request"),
                content: vec![UserContentBlock::Text(TextBlock { text: instruction })],
                source: UserSource::Runtime,
                kind: InboundKind::Message,
                timestamp: None,
            })];
            let model_request = ModelRequest {
                invocation: self.invocation.invocation_config(),
                messages,
                tools: Vec::new(),
                // Summary generation is not an inbound agent turn: it never
                // carries an Agent Status attachment and never carries the
                // attempt's Skill catalog attachment.
                agent_status: None,
                skill_catalog: None,
                continuation: None,
            };
            let mut stream = self
                .invocation
                .adapter()
                .stream(model_request, cancellation);
            let mut text = String::new();
            let mut state = SummaryStreamState::default();
            let mut finish_reason = None;
            while let Some(event) = stream.next().await {
                // Malformed canonical orderings are compaction failures,
                // never silently folded into a durable checkpoint.
                state.accept(&event)?;
                match event {
                    ModelEvent::Started
                    | ModelEvent::UsageUpdate { .. }
                    | ModelEvent::ReasoningDelta { .. }
                    | ModelEvent::ContinuationState { .. } => {}
                    ModelEvent::TextDelta { text: delta, .. } => text.push_str(&delta),
                    ModelEvent::RefusalDelta { .. } => {
                        return Err(summary_failed("summary generation refused"));
                    }
                    ModelEvent::ToolCallStarted { .. }
                    | ModelEvent::ToolCallArgumentsDelta { .. }
                    | ModelEvent::ToolCallCompleted { .. } => {
                        return Err(summary_failed("summary generation must not request tools"));
                    }
                    ModelEvent::Completed {
                        finish_reason: reason,
                        ..
                    } => {
                        finish_reason = Some(reason);
                    }
                    ModelEvent::Failed { error } => {
                        return Err(
                            if error.kind == crate::model::error::ModelErrorKind::Cancelled {
                                ContextError::new(
                                    ContextErrorKind::Cancelled,
                                    "summary generation cancelled",
                                )
                            } else {
                                summary_failed(&format!(
                                    "summary generation failed: {}",
                                    error.message
                                ))
                            },
                        );
                    }
                }
            }
            if !state.terminal {
                return Err(summary_failed(
                    "summary stream ended without a terminal event",
                ));
            }
            // The terminal finish reason is authoritative: a refusal with no
            // `RefusalDelta` and a tool-call completion with no delta are
            // still compaction failures, never summaries.
            match finish_reason {
                Some(crate::model::finish::ModelFinishReason::Refusal) => {
                    return Err(summary_failed("summary generation refused"));
                }
                Some(crate::model::finish::ModelFinishReason::ToolCalls) => {
                    return Err(summary_failed("summary generation must not request tools"));
                }
                _ => {}
            }
            // An empty or whitespace-only output erases history; it is never
            // a valid summary.
            if text.trim().is_empty() {
                return Err(summary_failed("summary generation produced no content"));
            }
            Ok(text)
        })
    }
}

fn summary_failed(message: &str) -> ContextError {
    ContextError::new(ContextErrorKind::SummaryFailed, message)
}

/// The canonical stream state of one summary generation.
///
/// Malformed adapter streams must never become durable compaction
/// checkpoints: the summary stream must start with `Started` (or a bare
/// terminal `Failed` for a request rejected before provider execution),
/// `Started` occurs at most once, `Completed` requires `Started`, and no
/// event follows the terminal event. This is the same canonical contract
/// the agent loop enforces, kept provider-neutral and without recursing
/// into `AgentExecution`.
#[derive(Debug, Default)]
struct SummaryStreamState {
    started: bool,
    terminal: bool,
}

impl SummaryStreamState {
    /// Accepts one event, validating the canonical stream ordering.
    ///
    /// # Errors
    ///
    /// Returns [`ContextErrorKind::SummaryFailed`] for a malformed
    /// ordering: content before `Started`, a duplicate `Started`,
    /// `Completed` without `Started`, or any event after the terminal.
    fn accept(&mut self, event: &ModelEvent) -> Result<(), ContextError> {
        if self.terminal {
            return Err(summary_failed(
                "summary stream event after the terminal event",
            ));
        }
        match event {
            ModelEvent::Started => {
                if self.started {
                    return Err(summary_failed("duplicate Started in the summary stream"));
                }
                self.started = true;
                Ok(())
            }
            ModelEvent::Failed { .. } => {
                self.terminal = true;
                Ok(())
            }
            ModelEvent::Completed { .. } => {
                if !self.started {
                    return Err(summary_failed("summary stream Completed without Started"));
                }
                self.terminal = true;
                Ok(())
            }
            _ => {
                if !self.started {
                    return Err(summary_failed("summary stream content before Started"));
                }
                Ok(())
            }
        }
    }
}
