//! The provider-neutral summary service.
//!
//! A compaction summary is generated by a [`ContextSummarizer`] that the
//! context runtime owns. The request boundary distinguishes the previous
//! checkpoint summary, the newly retired complete history, and any
//! split-turn retired prefix; these distinctions are never flattened before
//! the API boundary. Summary generation is agent-execution activity only: it
//! never recurses into `AgentExecution`, never exposes tools, never appends
//! to canonical history, and never emits committed-message events.

use futures_util::StreamExt;
use futures_util::future::BoxFuture;
use serde::{Deserialize, Serialize};

use crate::context::error::{ContextError, ContextErrorKind};
use crate::message::content::TextBlock;
use crate::message::types::{
    AgentContentBlock, InboundKind, MessageBlock, ToolMessageBlock, UserContentBlock,
    UserMessageBlock, UserSource,
};
use crate::model::adapter::ModelAdapter;
use crate::model::adapter::cancellation::ModelCancellation;
use crate::model::event::ModelEvent;
use crate::model::types::{ModelProtocol, ModelRequest, ReasoningEffort};
use crate::runtime::identity::MessageId;

/// One item of newly retired canonical content fed to the summarizer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SummaryInputItem {
    /// A whole retired canonical message.
    Message(MessageBlock),
    /// A retired residual content slice of a previously split agent message.
    AgentSlice {
        /// The identity of the source canonical agent message.
        message_id: MessageId,
        /// The retired content blocks.
        content: Vec<AgentContentBlock>,
    },
}

/// The retired prefix of one split turn, supplied intact to the summarizer.
///
/// Retired tool calls keep their tool results here: a large tool-call/result
/// pair is never silently dropped and never split across the summary and the
/// literal projection.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SplitTurnSummaryInput {
    /// The identity of the split canonical agent message.
    pub message_id: MessageId,
    /// The retired content prefix of that message.
    pub retired_prefix: Vec<AgentContentBlock>,
    /// The tool results of the tool calls contained in the retired prefix.
    pub retired_tool_messages: Vec<ToolMessageBlock>,
}

/// One summarizer request.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SummaryRequest {
    /// The previous checkpoint summary, when one exists.
    pub previous_summary: Option<String>,
    /// Only the canonical material newly retired since the previous
    /// checkpoint; history already covered by the previous checkpoint is
    /// never re-fed.
    pub newly_retired: Vec<SummaryInputItem>,
    /// The retired prefix of a split turn, when this compaction splits one.
    pub split_turn_prefix: Option<SplitTurnSummaryInput>,
}

impl SummaryRequest {
    /// Whether this request covers at least one additional compactable unit
    /// beyond the previous checkpoint.
    #[must_use]
    pub fn advances_coverage(&self) -> bool {
        !self.newly_retired.is_empty()
            || self
                .split_turn_prefix
                .as_ref()
                .is_some_and(|split| !split.retired_prefix.is_empty())
    }
}

/// The summary service.
pub trait ContextSummarizer: Send + Sync {
    /// Generates the textual summary of one request.
    ///
    /// The returned future is owned by the summarizer and must observe
    /// `cancellation`; cancellation may abort the summary.
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: ModelCancellation,
    ) -> BoxFuture<'_, Result<String, ContextError>>;
}

/// The model configuration of one summary generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SummaryModelConfig {
    /// Provider model identifier.
    pub model: String,
    /// Canonical protocol.
    pub protocol: ModelProtocol,
    /// Reasoning effort.
    pub reasoning: ReasoningEffort,
    /// The runtime-resolved effective maximum output tokens, shared with the
    /// execution; no adapter-local generation limit is invented.
    pub max_output_tokens: u32,
}

/// The production-capable summarizer backed by the canonical model adapter.
///
/// The summary request is a canonical one-off `ModelRequest`: no tools, no
/// continuation, the execution's model/protocol/reasoning and runtime
/// output budget, and a deterministic instruction plus the serialized
/// request input. A refusal, a tool request, an invalid stream, or a model
/// failure is a compaction failure, and any provider continuation emitted by
/// the one-off request is discarded: summary activity never contaminates the
/// attempt's continuation or usage state.
pub struct ModelBackedSummarizer<'a> {
    adapter: &'a dyn ModelAdapter,
    config: SummaryModelConfig,
}

impl<'a> ModelBackedSummarizer<'a> {
    /// Creates a summarizer over the execution's adapter and model
    /// configuration.
    #[must_use]
    pub fn new(adapter: &'a dyn ModelAdapter, config: SummaryModelConfig) -> Self {
        Self { adapter, config }
    }

    /// The deterministic summary instruction text.
    #[must_use]
    pub const fn instruction() -> &'static str {
        "Summarize the following conversation history for continuation. \
         Preserve all decisions, tool outcomes, and open threads; produce a \
         compact factual summary. Output only the summary text."
    }

    /// Serializes the request input deterministically for the model.
    ///
    /// The serialization is canonical JSON over runtime-owned types and is
    /// a pure function of the request.
    ///
    /// # Panics
    ///
    /// Panics only if the canonical request input fails to serialize, which
    /// is unreachable for the canonical runtime-owned types.
    #[must_use]
    pub fn serialize_input(request: &SummaryRequest) -> String {
        serde_json::to_string(request).expect("summary request serializes")
    }
}

impl ContextSummarizer for ModelBackedSummarizer<'_> {
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: ModelCancellation,
    ) -> BoxFuture<'_, Result<String, ContextError>> {
        Box::pin(async move {
            let input = ModelBackedSummarizer::serialize_input(&request);
            let instruction = format!("{}\n\n{}", ModelBackedSummarizer::instruction(), input);
            let messages = vec![MessageBlock::User(UserMessageBlock {
                id: MessageId::new("summary-request"),
                content: vec![UserContentBlock::Text(TextBlock { text: instruction })],
                source: UserSource::Runtime,
                kind: InboundKind::Message,
            })];
            let model_request = ModelRequest {
                model: self.config.model.clone(),
                protocol: self.config.protocol,
                messages,
                tools: Vec::new(),
                reasoning: self.config.reasoning,
                max_output_tokens: self.config.max_output_tokens,
                continuation: None,
            };
            let mut stream = self.adapter.stream(model_request, cancellation);
            let mut text = String::new();
            let mut terminal = false;
            while let Some(event) = stream.next().await {
                match event {
                    ModelEvent::Started
                    | ModelEvent::UsageUpdate { .. }
                    | ModelEvent::ReasoningDelta { .. }
                    | ModelEvent::ContinuationState { .. } => {}
                    ModelEvent::TextDelta { text: delta, .. } => text.push_str(&delta),
                    ModelEvent::RefusalDelta { .. } => {
                        return Err(summary_failed("summary generation refused"));
                    }
                    ModelEvent::ToolCallStarted { .. }
                    | ModelEvent::ToolCallArgumentsDelta { .. }
                    | ModelEvent::ToolCallCompleted { .. } => {
                        return Err(summary_failed("summary generation must not request tools"));
                    }
                    ModelEvent::Completed { .. } => {
                        terminal = true;
                        break;
                    }
                    ModelEvent::Failed { error } => {
                        return Err(
                            if error.kind == crate::model::error::ModelErrorKind::Cancelled {
                                ContextError::new(
                                    ContextErrorKind::Cancelled,
                                    "summary generation cancelled",
                                )
                            } else {
                                summary_failed(&format!(
                                    "summary generation failed: {}",
                                    error.message
                                ))
                            },
                        );
                    }
                }
            }
            if !terminal {
                return Err(summary_failed(
                    "summary stream ended without a terminal event",
                ));
            }
            Ok(text)
        })
    }
}

fn summary_failed(message: &str) -> ContextError {
    ContextError::new(ContextErrorKind::SummaryFailed, message)
}
