//! The provider-neutral summary service.
//!
//! A compaction summary is generated by a [`ContextSummarizer`] that the
//! context runtime owns. Since M7.5 (Issue #54) the request boundary is
//! derived directly from the **selected span of complete canonical active
//! messages** of the current Conversation Surface. There is no separate
//! "previous summary" truth: when a previous compaction summary
//! is still active, it is simply one canonical
//! `User(Runtime / CompactionSummary)` message inside the selected span.
//!
//! Since Issue #140 the production instruction requires one fixed structured
//! Markdown contract (Goal, Constraints & Preferences, Progress, Key
//! Decisions, Next Steps, Critical Context). The generated body is semantic
//! content only: the cumulative file-operation facts of the transition are
//! extracted deterministically from the retired span's canonical tool calls
//! into typed `CompactionSummaryMetadata` (see
//! [`crate::context::compaction_metadata`]), and the generated prose is never
//! parsed back into facts.
//!
//! Summary generation is runtime compaction activity only: it never recurses
//! into `AgentExecution`, never exposes tools, never carries Agent Status or
//! the Skill catalog, never carries provider continuation, and never commits
//! anything to the Message Ledger.

use std::fmt::Write as _;
use std::sync::Arc;

use futures_util::StreamExt;
use futures_util::future::{BoxFuture, pending};
use serde::{Deserialize, Serialize};

use crate::context::error::{ContextError, ContextErrorKind};
use crate::message::content::TextBlock;
use crate::message::types::{
    AssistantContentBlock, AssistantMessageBlock, InboundKind, MessageBlock, ToolMessageBlock,
    UserContentBlock, UserMessageBlock, UserSource,
};
use crate::model::adapter::ModelStreamItem;
use crate::model::deadline::{ModelRequestDeadline, ModelTimeoutPolicy};
use crate::model::event::ModelEvent;
use crate::model::generation::GenerationGuard;
use crate::model::invocation::ResolvedModelInvocation;
use crate::model::types::ModelRequest;
use crate::runtime::cancellation::CancellationSignal;
use crate::runtime::identity::MessageId;
use crate::runtime::monotonic::MonotonicClock;
use crate::tools::types::{ToolExecutionStatus, ToolResultContent};

/// One summarizer request.
///
/// The request carries exactly the complete canonical messages of the
/// selected Surface span, in Surface order. Nothing is flattened, nothing is
/// partial, and no hidden previous-summary channel exists beside it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SummaryRequest {
    /// The selected span of complete canonical active messages, in Surface
    /// order. A still-active previous compaction summary appears here as an
    /// ordinary `User(Runtime / CompactionSummary)` message.
    pub retired: Vec<MessageBlock>,
}

/// The exact provider-neutral model input assembled for one summary request.
///
/// Both compaction planning and [`ModelBackedSummarizer`] consume this value:
/// the fixed instruction, the deterministic rendered transcript, and the
/// canonical runtime User wrapper therefore cannot drift between estimation
/// and the production invocation.
#[derive(Debug, Clone, PartialEq)]
pub struct SummaryModelInput {
    /// The complete canonical messages sent to the summary model.
    pub messages: Vec<MessageBlock>,
}

/// The maximum characters of one tool result rendered into a summary
/// request.
///
/// Tool output dominates the token cost of an agentic conversation and is
/// the least summary-relevant part of it: the head of a result carries the
/// outcome, the tail is bulk. Without this bound the rendered span is
/// *larger* than the conversation it replaces, which is exactly how a
/// compaction triggered by a context overflow overflows again.
pub const SUMMARY_TOOL_RESULT_MAX_CHARS: usize = 2_000;

/// The maximum characters of one reasoning block rendered into a summary
/// request. Replayed reasoning is bulky and historical; the summary needs
/// its gist, never its full text.
pub const SUMMARY_REASONING_MAX_CHARS: usize = 1_000;

/// The maximum characters of one rendered tool-call argument payload.
pub const SUMMARY_TOOL_ARGUMENTS_MAX_CHARS: usize = 1_000;

impl SummaryRequest {
    /// Whether this request covers at least one canonical message.
    #[must_use]
    pub fn advances_coverage(&self) -> bool {
        !self.retired.is_empty()
    }

    /// Renders the retired span as the deterministic plain-text transcript
    /// the summary model reads.
    ///
    /// This is deliberately **not** the canonical JSON encoding. Canonical
    /// JSON is the durable interchange format, and pushing it through a
    /// model request costs far more tokens than the conversation it
    /// describes: every structural quote, field name, and escaped newline
    /// becomes input. The rendering below is a pure, deterministic function
    /// of the retired span that keeps what a summary needs — who said what,
    /// which tools ran with which arguments, and how they ended — while
    /// bounding the bulk contributors (tool results, replayed reasoning,
    /// tool-call arguments).
    #[must_use]
    pub fn render_transcript(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        for message in &self.retired {
            match message {
                MessageBlock::User(user) => render_user(user, &mut parts),
                MessageBlock::Assistant(assistant) => render_assistant(assistant, &mut parts),
                MessageBlock::Tool(tool) => render_tool(tool, &mut parts),
            }
        }
        parts.join("\n\n")
    }

    /// Assembles the exact canonical model input used by the production
    /// summary invocation.
    #[must_use]
    pub fn model_input(&self) -> SummaryModelInput {
        let instruction = format!(
            "{}\n\n<retired-conversation>\n{}\n</retired-conversation>",
            SUMMARY_INSTRUCTION,
            self.render_transcript()
        );
        SummaryModelInput {
            messages: vec![MessageBlock::User(UserMessageBlock {
                id: MessageId::new("summary-request"),
                content: vec![UserContentBlock::Text(TextBlock { text: instruction })],
                source: UserSource::Runtime,
                kind: InboundKind::Message,
                timestamp: None,
            })],
        }
    }
}

/// Truncates on a character boundary, reporting how much was dropped.
///
/// Truncation is always announced: a summary model must never be able to
/// mistake a cut-off tool result for a complete one.
fn truncate_for_summary(text: &str, max_chars: usize) -> String {
    let mut indices = text.char_indices();
    let Some((cut, _)) = indices.nth(max_chars) else {
        return text.to_owned();
    };
    let dropped = text[cut..].chars().count();
    format!(
        "{}\n[... {dropped} more characters truncated]",
        &text[..cut]
    )
}

/// The transcript label of one inbound message's provenance and kind.
fn user_label(user: &UserMessageBlock) -> String {
    match (&user.kind, &user.source) {
        (InboundKind::CompactionSummary(_), _) => "Earlier summary".to_owned(),
        (InboundKind::Context(kind), _) => format!("Runtime context ({kind:?})"),
        (_, UserSource::Runtime) => "Runtime".to_owned(),
        (_, UserSource::Agent { agent_id }) => format!("Agent {agent_id}"),
        (_, UserSource::Fleet) => "Fleet".to_owned(),
        (_, UserSource::ExternalSystem) => "External system".to_owned(),
        (_, UserSource::Extension { contributor }) => format!("Extension {contributor}"),
        (_, UserSource::Human) => "User".to_owned(),
    }
}

fn render_user(user: &UserMessageBlock, parts: &mut Vec<String>) {
    let mut rendered = String::new();
    for block in &user.content {
        if !rendered.is_empty() {
            rendered.push('\n');
        }
        match block {
            UserContentBlock::Text(text) => rendered.push_str(&text.text),
            UserContentBlock::Image(image) => {
                let _ = write!(rendered, "[image {}]", image.artifact_id);
            }
            UserContentBlock::File(file) => {
                let _ = write!(
                    rendered,
                    "[file {}]",
                    file.name.as_deref().unwrap_or("attachment")
                );
            }
        }
    }
    if rendered.is_empty() {
        return;
    }
    parts.push(format!("[{}]: {rendered}", user_label(user)));
}

fn render_assistant(assistant: &AssistantMessageBlock, parts: &mut Vec<String>) {
    for block in &assistant.content {
        match block {
            AssistantContentBlock::Text(text) if !text.text.is_empty() => {
                parts.push(format!("[Assistant]: {}", text.text));
            }
            AssistantContentBlock::Reasoning(reasoning) => {
                if let Some(text) = reasoning.text.as_deref()
                    && !text.is_empty()
                {
                    parts.push(format!(
                        "[Assistant thinking]: {}",
                        truncate_for_summary(text, SUMMARY_REASONING_MAX_CHARS)
                    ));
                }
            }
            AssistantContentBlock::ToolCall(call) => {
                let arguments = serde_json::to_string(&call.arguments)
                    .unwrap_or_else(|_| "[unserializable]".to_owned());
                parts.push(format!(
                    "[Tool call {}]: {}({})",
                    call.id,
                    call.name,
                    truncate_for_summary(&arguments, SUMMARY_TOOL_ARGUMENTS_MAX_CHARS)
                ));
            }
            AssistantContentBlock::Refusal(refusal) => {
                parts.push(format!("[Assistant refusal]: {}", refusal.text));
            }
            AssistantContentBlock::Image(image) => {
                parts.push(format!("[Assistant image]: {}", image.artifact_id));
            }
            AssistantContentBlock::Text(_) => {}
        }
    }
}

fn render_tool(tool: &ToolMessageBlock, parts: &mut Vec<String>) {
    let mut rendered = String::new();
    for content in &tool.result.content {
        if !rendered.is_empty() {
            rendered.push('\n');
        }
        match content {
            ToolResultContent::Text(text) => rendered.push_str(&text.text),
            ToolResultContent::Json { value } => rendered.push_str(
                &serde_json::to_string(value).unwrap_or_else(|_| "[unserializable]".to_owned()),
            ),
            ToolResultContent::File(file) => {
                let _ = write!(
                    rendered,
                    "[file {}]",
                    file.name.as_deref().unwrap_or("artifact")
                );
            }
            ToolResultContent::Image(image) => {
                let _ = write!(rendered, "[image {}]", image.artifact_id);
            }
        }
    }
    let status = match &tool.result.status {
        ToolExecutionStatus::Success => "success".to_owned(),
        ToolExecutionStatus::Failed { error } => format!("failed: {error}"),
        ToolExecutionStatus::Denied { reason } => format!("denied: {reason}"),
        // Cancelled, TimedOut, and OutcomeUnknown keep their full typed
        // model-facing feedback so the semantic distinction between a
        // confirmed terminal settlement and an unknown external outcome
        // survives summarization.
        status @ (ToolExecutionStatus::Cancelled { .. }
        | ToolExecutionStatus::TimedOut
        | ToolExecutionStatus::OutcomeUnknown { .. }) => status
            .feedback_text()
            .expect("non-success status has model-facing text"),
    };
    parts.push(format!(
        "[Tool result {} ({status})]: {}",
        tool.tool_id,
        truncate_for_summary(&rendered, SUMMARY_TOOL_RESULT_MAX_CHARS)
    ));
}

/// The summary service.
pub trait ContextSummarizer: Send + Sync {
    /// Generates the textual summary of one request.
    ///
    /// The returned text is the structured Markdown summary body only. The
    /// deterministic file half of the transition — typed
    /// `CompactionSummaryMetadata` extraction and the derived
    /// `<read-files>`/`<modified-files>` rendering — is applied by the
    /// compaction preparation, never by this service.
    ///
    /// The returned future is owned by the summarizer and must observe
    /// `cancellation`; cancellation may abort the summary.
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: CancellationSignal,
    ) -> BoxFuture<'_, Result<String, ContextError>>;
}

/// The production summarizer backed by a frozen resolved summary-model
/// invocation.
///
/// For automatic compaction the invocation is the attempt's frozen summary
/// resolution. Manual compaction freezes the same session resolution at its
/// idle admission boundary. In `session` mode this is the primary invocation;
/// in `explicit` mode it is the separately resolved summary invocation,
/// optionally narrowed by the context plane's summary output safety cap.
/// There is deliberately no independent "summary provider config" system.
///
/// The summary request is a canonical one-off `ModelRequest`: no tools, no
/// Agent Status, no Skill catalog, no continuation, and a deterministic
/// instruction plus the serialized request input. A refusal (with or without
/// a `RefusalDelta`), a tool request, an invalid stream, a model failure, or
/// an empty/whitespace-only output is a compaction failure, and any provider
/// continuation emitted by the one-off request is discarded: summary
/// activity never contaminates the attempt's continuation or usage state.
pub struct ModelBackedSummarizer {
    invocation: ResolvedModelInvocation,
    model_timeout_policy: ModelTimeoutPolicy,
    monotonic_clock: Arc<dyn MonotonicClock>,
}

/// The fixed structured summary instruction (Issue #140).
///
/// The production summarizer requires one exact Markdown contract — Goal,
/// Constraints & Preferences, Progress (Done / In Progress / Blocked), Key
/// Decisions, Next Steps, Critical Context — rather than free-form text.
/// Structured means this fixed contract only: rustX does not parse the
/// headings back into fields, and the file-operation facts of the transition
/// come from canonical tool-call extraction, never from the generated prose.
const SUMMARY_INSTRUCTION: &str = r#"Summarize the following retired conversation history so a later primary model turn can continue the work without re-reading the retired span. When the retired history contains an earlier summary, update and merge it into one coherent new summary; do not repeat it verbatim as a separate section.

Output the summary in EXACTLY this Markdown structure, with these exact headings and nothing before the first heading or after the last section:

## Goal

[What is the user trying to accomplish?]

## Constraints & Preferences

- [Constraints, preferences, requirements]
- [Or "(none)"]

## Progress

### Done

- [x] [Completed work]

### In Progress

- [ ] [Current work]

### Blocked

- [Current blockers]

## Key Decisions

- **[Decision]**: [Brief rationale]

## Next Steps

1. [Ordered next action]

## Critical Context

- [Important data, examples, references]
- [Or "(none)"]

Preserve relevant exact details: file paths, type and function names, important error strings, critical values, user constraints, and the rationale behind key decisions. Treat Agent Status and other runtime observations as historical evidence, not live authority: for example, observations that a task was running at one time and completed later may be summarized as having run earlier and completed, never as a claim about what is currently running or completed. If an Agent Status section is absent from a later observation, do not infer lifecycle completion or disappearance unless that section's explicit contract says absence has that meaning. Output only the summary Markdown; do not wrap it in code fences."#;

impl ModelBackedSummarizer {
    /// Creates a summarizer over one resolved summary invocation.
    #[must_use]
    pub fn new(
        invocation: ResolvedModelInvocation,
        model_timeout_policy: ModelTimeoutPolicy,
        monotonic_clock: Arc<dyn MonotonicClock>,
    ) -> Self {
        Self {
            invocation,
            model_timeout_policy,
            monotonic_clock,
        }
    }

    /// The resolved invocation this summarizer sends with.
    #[must_use]
    pub const fn invocation(&self) -> &ResolvedModelInvocation {
        &self.invocation
    }

    /// The deterministic summary instruction text.
    #[must_use]
    pub const fn instruction() -> &'static str {
        SUMMARY_INSTRUCTION
    }

    /// Renders the request input deterministically for the model.
    ///
    /// The rendering is a pure function of the request; see
    /// [`SummaryRequest::render_transcript`] for why it is a bounded plain
    /// transcript rather than the canonical JSON encoding.
    #[must_use]
    pub fn serialize_input(request: &SummaryRequest) -> String {
        request.render_transcript()
    }
}

impl ContextSummarizer for ModelBackedSummarizer {
    #[allow(clippy::too_many_lines)] // one explicit summary stream/failure boundary
    fn summarize(
        &self,
        request: SummaryRequest,
        cancellation: CancellationSignal,
    ) -> BoxFuture<'_, Result<String, ContextError>> {
        Box::pin(async move {
            let input = request.model_input();
            let model_request = ModelRequest {
                invocation: self.invocation.invocation_config(),
                // The summarizer has a structurally canonical-only input
                // boundary. Request-only execution-recovery context cannot
                // be represented by `SummaryModelInput`, so it cannot be
                // forwarded into a summary request accidentally.
                messages: crate::model::input::canonical_input(&input.messages),
                tools: Vec::new(),
                // Summary generation is not an inbound Assistant turn: it never
                // carries primary-step dynamic context. Agent Status is a
                // primary-request User fact, and Skill guidance is a
                // primary-request system section; neither belongs here.
                effective_system_prompt: String::new(),
                continuation: None,
            };
            // Summary dispatch has its own request-local deadline. It starts
            // before the synchronous adapter dispatch and never uses the
            // primary AgentCancellation authority.
            let mut deadline = ModelRequestDeadline::new(
                self.model_timeout_policy,
                self.monotonic_clock.now_millis(),
            );
            // Summary generation is a model generation like any other: it can
            // degenerate and it can stream past its output budget while
            // remaining perfectly live. It gets the same provider-independent
            // guard as the primary path, enforcing the policy the summary
            // invocation itself resolves, and maps the result through this
            // module's existing summary-failure boundary instead of entering
            // generic model retry — exactly as the shared request deadline
            // already does.
            let mut guard = GenerationGuard::new(self.invocation.generation_safety_policy());
            let mut stream = self
                .invocation
                .adapter()
                .stream(model_request, cancellation.clone());
            let mut text = String::new();
            let mut state = SummaryStreamState::default();
            let mut finish_reason = None;
            loop {
                let timeout_wait: BoxFuture<'static, ()> = match deadline.deadline_millis() {
                    Some(deadline_millis) => {
                        self.monotonic_clock.wait_until_millis(deadline_millis)
                    }
                    None => Box::pin(pending()),
                };
                let next = tokio::select! {
                    biased;
                    item = stream.next() => item,
                    () = cancellation.cancelled() => {
                        return Err(ContextError::new(
                            ContextErrorKind::Cancelled,
                            "summary generation cancelled",
                        ));
                    }
                    () = timeout_wait => {
                        drop(stream);
                        return Err(summary_failed("summary generation timed out"));
                    }
                };
                let Some(item) = next else {
                    break;
                };
                // The shared state machine owns provider-item classification and
                // phase transitions. Publication/compaction work never
                // reaches this call and therefore cannot reset a deadline.
                deadline.observe(&item, self.monotonic_clock.now_millis());
                if let Some(failure) = guard.observe(&item) {
                    drop(stream);
                    return Err(summary_failed(&format!(
                        "summary generation was discarded: {}",
                        failure.message()
                    )));
                }
                // Malformed canonical orderings are compaction failures,
                // never silently folded into a canonical message.
                state.accept(&item)?;
                match item {
                    ModelStreamItem::Progress(_) => {}
                    ModelStreamItem::Event(event) => match event {
                        ModelEvent::Started
                        | ModelEvent::UsageUpdate { .. }
                        | ModelEvent::ReasoningDelta { .. }
                        | ModelEvent::ContinuationState { .. } => {}
                        ModelEvent::TextDelta { text: delta, .. } => text.push_str(&delta),
                        ModelEvent::RefusalDelta { .. } => {
                            return Err(summary_failed("summary generation refused"));
                        }
                        ModelEvent::ToolCallStarted { .. }
                        | ModelEvent::ToolCallArgumentsDelta { .. }
                        | ModelEvent::ToolCallCompleted { .. } => {
                            return Err(summary_failed(
                                "summary generation must not request tools",
                            ));
                        }
                        ModelEvent::Completed {
                            finish_reason: reason,
                            ..
                        } => {
                            finish_reason = Some(reason);
                        }
                        ModelEvent::Failed { error } => {
                            return Err(match error.kind {
                                crate::model::error::ModelErrorKind::Cancelled => {
                                    ContextError::new(
                                        ContextErrorKind::Cancelled,
                                        "summary generation cancelled",
                                    )
                                }
                                // The summary request itself did not fit the
                                // summary model. This is not a dead end: it is
                                // evidence that the planned span was estimated
                                // too optimistically, and the pipeline replans
                                // against a smaller budget.
                                crate::model::error::ModelErrorKind::ContextWindowExceeded => {
                                    ContextError::new(
                                        ContextErrorKind::SummaryInputTooLarge,
                                        format!(
                                            "the summary request exceeded the summary model context window: {}",
                                            error.message
                                        ),
                                    )
                                }
                                _ => summary_failed(&format!(
                                    "summary generation failed: {}",
                                    error.message
                                )),
                            });
                        }
                    },
                }
            }
            if !state.terminal {
                return Err(summary_failed(
                    "summary stream ended without a terminal event",
                ));
            }
            // The terminal finish reason is authoritative: a refusal with no
            // `RefusalDelta` and a tool-call completion with no delta are
            // still compaction failures, never summaries.
            match finish_reason {
                Some(crate::model::finish::ModelFinishReason::Refusal) => {
                    return Err(summary_failed("summary generation refused"));
                }
                Some(crate::model::finish::ModelFinishReason::ToolCalls) => {
                    return Err(summary_failed("summary generation must not request tools"));
                }
                // A summary truncated at the provider's token limit is not a
                // summary: it replaces retired history with a sentence that
                // stops mid-thought. The same fail-closed rule the Agent Loop
                // applies before its canonical commit applies here, before
                // compaction can commit this text.
                Some(reason) => {
                    if let Some(failure) = GenerationGuard::classify_completion(&reason) {
                        return Err(summary_failed(&format!(
                            "summary generation was discarded: {}",
                            failure.message()
                        )));
                    }
                }
                None => {}
            }
            // An empty or whitespace-only output erases history; it is never
            // a valid summary.
            if text.trim().is_empty() {
                return Err(summary_failed("summary generation produced no content"));
            }
            Ok(text)
        })
    }
}

fn summary_failed(message: &str) -> ContextError {
    ContextError::new(ContextErrorKind::SummaryFailed, message)
}

/// The canonical stream state of one summary generation.
///
/// Malformed adapter streams must never become durable compaction
/// summary messages: the summary stream must start with `Started` (or a bare
/// terminal `Failed` for a request rejected before provider execution),
/// `Started` occurs at most once, `Completed` requires `Started`, and no
/// event follows the terminal event. Ephemeral progress is accepted only
/// after `Started` and never changes the canonical state. This is the same
/// canonical contract
/// the agent loop enforces, kept provider-neutral and without recursing
/// into `AgentExecution`.
#[derive(Debug, Default)]
struct SummaryStreamState {
    started: bool,
    terminal: bool,
}

impl SummaryStreamState {
    /// Accepts one stream item, validating canonical event ordering while
    /// keeping progress ephemeral.
    ///
    /// # Errors
    ///
    /// Returns [`ContextErrorKind::SummaryFailed`] for a malformed
    /// ordering: content before `Started`, a duplicate `Started`,
    /// `Completed` without `Started`, or any event after the terminal.
    fn accept(&mut self, item: &ModelStreamItem) -> Result<(), ContextError> {
        if self.terminal {
            return Err(summary_failed(
                "summary stream item after the terminal event",
            ));
        }
        let ModelStreamItem::Event(event) = item else {
            if self.started {
                return Ok(());
            }
            return Err(summary_failed("summary stream progress before Started"));
        };
        match event {
            ModelEvent::Started => {
                if self.started {
                    return Err(summary_failed("duplicate Started in the summary stream"));
                }
                self.started = true;
                Ok(())
            }
            ModelEvent::Failed { .. } => {
                self.terminal = true;
                Ok(())
            }
            ModelEvent::Completed { .. } => {
                if !self.started {
                    return Err(summary_failed("summary stream Completed without Started"));
                }
                self.terminal = true;
                Ok(())
            }
            _ => {
                if !self.started {
                    return Err(summary_failed("summary stream content before Started"));
                }
                Ok(())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{ModelBackedSummarizer, SUMMARY_TOOL_RESULT_MAX_CHARS, SummaryRequest};
    use crate::message::content::TextBlock;
    use crate::message::types::{
        InboundKind, MessageBlock, ToolMessageBlock, UserContentBlock, UserMessageBlock, UserSource,
    };
    use crate::runtime::identity::{MessageId, ToolCallId, ToolId};
    use crate::runtime::types::CancellationReason;
    use crate::tools::types::{
        ToolCancellationPhase, ToolExecutionResult, ToolExecutionStatus, ToolResultContent,
    };

    fn request() -> SummaryRequest {
        SummaryRequest {
            retired: vec![MessageBlock::User(UserMessageBlock {
                id: MessageId::new("retired-1"),
                content: vec![UserContentBlock::Text(TextBlock {
                    text: "same payload".to_owned(),
                })],
                source: UserSource::Human,
                kind: InboundKind::Message,
                timestamp: None,
            })],
        }
    }

    /// The shared assembly boundary includes the instruction, serialized
    /// request envelope, and canonical runtime User wrapper exactly once.
    #[test]
    fn summary_model_input_is_deterministic_and_complete() {
        let request = request();
        let first = request.model_input();
        assert_eq!(first, request.model_input());
        assert_eq!(first.messages.len(), 1);
        assert!(
            first
                .messages
                .iter()
                .all(|message| matches!(message, MessageBlock::User(_))),
            "the summary boundary is structurally canonical-only"
        );
        let MessageBlock::User(wrapper) = &first.messages[0] else {
            panic!("summary input must use the canonical User role");
        };
        assert_eq!(wrapper.id, MessageId::new("summary-request"));
        assert_eq!(wrapper.source, UserSource::Runtime);
        assert_eq!(wrapper.kind, InboundKind::Message);
        let UserContentBlock::Text(text) = &wrapper.content[0] else {
            panic!("summary input must use a text wrapper");
        };
        assert_eq!(
            text.text,
            format!(
                "{}\n\n<retired-conversation>\n{}\n</retired-conversation>",
                ModelBackedSummarizer::instruction(),
                request.render_transcript()
            )
        );
    }

    /// The rendered transcript is plain text, not canonical JSON, and it
    /// bounds the bulk contributors. A summary request must never be larger
    /// than the history it replaces.
    #[test]
    fn rendered_transcript_bounds_tool_output() {
        let request = SummaryRequest {
            retired: vec![MessageBlock::Tool(ToolMessageBlock {
                id: MessageId::new("tool-1"),
                tool_call_id: ToolCallId::new("call-1"),
                tool_id: ToolId::new("tool-bash"),
                result: ToolExecutionResult {
                    status: ToolExecutionStatus::Success,
                    content: vec![ToolResultContent::Text(TextBlock {
                        text: "x".repeat(50_000),
                    })],
                    duration_ms: 1,
                    exit_code: Some(0),
                    artifacts: Vec::new(),
                    truncation: None,
                    managed_output: None,
                },
            })],
        };
        let rendered = request.render_transcript();
        assert!(
            rendered.chars().count() < SUMMARY_TOOL_RESULT_MAX_CHARS + 200,
            "a tool result must be truncated into the summary request"
        );
        assert!(rendered.contains("more characters truncated"));
        assert!(
            rendered.len()
                < serde_json::to_vec(&request.retired)
                    .expect("canonical messages serialize")
                    .len(),
            "the rendered transcript must be smaller than the canonical encoding"
        );
    }

    #[test]
    fn issue136_rendered_transcript_explains_cancellation_phase() {
        for (reason, reason_label) in [
            (CancellationReason::UserRequested, "user_requested"),
            (CancellationReason::RuntimeShutdown, "runtime_shutdown"),
        ] {
            for (phase, required) in [
                (
                    ToolCancellationPhase::BeforeStart,
                    "rustX did not start execution",
                ),
                (
                    ToolCancellationPhase::DuringExecution,
                    "Partial side effects may have occurred",
                ),
            ] {
                let request = SummaryRequest {
                    retired: vec![MessageBlock::Tool(ToolMessageBlock {
                        id: MessageId::new("tool-cancelled"),
                        tool_call_id: ToolCallId::new("call-cancelled"),
                        tool_id: ToolId::new("tool-cancelled"),
                        result: ToolExecutionResult {
                            status: ToolExecutionStatus::Cancelled { reason, phase },
                            content: Vec::new(),
                            duration_ms: 0,
                            exit_code: None,
                            artifacts: Vec::new(),
                            truncation: None,
                            managed_output: None,
                        },
                    })],
                };
                let rendered = request.render_transcript();
                assert!(rendered.contains(reason_label));
                assert!(rendered.contains(required));
            }
        }
    }

    /// Issue #202: a proven terminal timeout and an admitted unknown outcome
    /// keep their distinct typed feedback in the summary request — the
    /// unknown outcome never collapses into generic failure wording.
    #[test]
    fn issue202_rendered_transcript_distinguishes_timeout_from_unknown_outcome() {
        for (status, required) in [
            (
                ToolExecutionStatus::TimedOut,
                "established terminal settlement",
            ),
            (
                ToolExecutionStatus::OutcomeUnknown {
                    detail: "the runtime restarted before a durable outcome was committed"
                        .to_owned(),
                },
                "could not establish its final external outcome",
            ),
        ] {
            let request = SummaryRequest {
                retired: vec![MessageBlock::Tool(ToolMessageBlock {
                    id: MessageId::new("tool-unknown"),
                    tool_call_id: ToolCallId::new("call-unknown"),
                    tool_id: ToolId::new("tool-unknown"),
                    result: ToolExecutionResult {
                        status,
                        content: Vec::new(),
                        duration_ms: 0,
                        exit_code: None,
                        artifacts: Vec::new(),
                        truncation: None,
                        managed_output: None,
                    },
                })],
            };
            let rendered = request.render_transcript();
            assert!(
                rendered.contains(required),
                "the summary preserves the typed status distinction: {rendered}"
            );
            assert!(
                !rendered.contains("failed:"),
                "an unknown outcome is not reported as a failure: {rendered}"
            );
        }
    }

    /// Truncation never splits a multi-byte character.
    #[test]
    fn truncation_respects_character_boundaries() {
        let text = "汉".repeat(10);
        let truncated = super::truncate_for_summary(&text, 4);
        assert!(truncated.starts_with("汉汉汉汉\n[..."));
        assert_eq!(super::truncate_for_summary(&text, 10), text);
        assert_eq!(super::truncate_for_summary(&text, 99), text);
    }

    /// The production instruction requires the fixed Pi-style structured
    /// Markdown contract (Issue #140) and no longer advertises free-form
    /// output.
    #[test]
    fn summary_instruction_requires_the_structured_contract() {
        let instruction = ModelBackedSummarizer::instruction();
        for section in [
            "## Goal",
            "## Constraints & Preferences",
            "## Progress",
            "### Done",
            "### In Progress",
            "### Blocked",
            "## Key Decisions",
            "## Next Steps",
            "## Critical Context",
        ] {
            assert!(
                instruction.contains(section),
                "the structured summary contract requires {section}"
            );
        }
        assert!(
            instruction.contains("EXACTLY this Markdown structure"),
            "the structure is a fixed contract, not guidance"
        );
        assert!(
            !instruction.contains("free-form"),
            "free-form output is no longer advertised"
        );
        for exact_detail in [
            "file paths",
            "type and function names",
            "error strings",
            "critical values",
            "user constraints",
        ] {
            assert!(
                instruction.contains(exact_detail),
                "the contract requires preserving {exact_detail}"
            );
        }
    }
}
